---
abstract: 'Generates rules for many firewalls from a central ruleset.'
author:
  - 'Heinz Knutzen <heinz.knutzen@dataport.de>'
build_requires:
  Capture::Tiny: '0'
  Carp: '0'
  File::Path: '0'
  File::Spec::Functions: '0'
  File::Temp: '0'
  IPC::Run3: '0'
  JSON: '0'
  NetAddr::IP::Util: '0'
  Netspoc::Compiler::Common: '0'
  POSIX: '0'
  Regexp::IPv6: '0'
  Test::Differences: '0'
  Test::More: '0'
  lib: '0'
  open: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Netspoc
version: '6.023'
x_generated_by_perl: v5.26.0
x_serialization_backend: 'YAML::Tiny version 1.73'
