=head1 NAME

netspoc - network security policy compiler

=head1 SYNOPSIS

netspoc input-dir output-dir

netspoc input-file output-dir

=head1 DESCRIPTION

The network security compiler takes a policy description
recursively from all files in input-dir and places one file for
each managed device into output-dir.
Alternatively input may be read from a single input-file; this
is mainly used for small examples or testing.

=head1 OPTIONS

Options may currently only be changed in the source file of netspoc.

=over 4

=item $verbose = [0|1];

Controls whether netspoc shows output about different
compiler phases and statistics on standard error.

=item $comment_acls = [0|1];

Add a comment line before each generated ACL entry.
Comments use names of network objects as defined in 
the topology.

=item $comment_routes = [0|1];

Add a comment line before each generated routing entry.
Comments use names of network objects as defined in 
the topology.

=item $warn_unused_groups = [0|1]

Gives warning for unused groups and service groups.

=item $strict_subnets = [0|1|'warn']

Allow subnets only if the enclosing network is declared as 'route_hint'
or if the subnet is declared as 'subnet_of'.
If set to 'warn', netspoc only warns about undeclared subnet relations.

=item $ignore_files = qr/^CVS$|^RCS$|^.#|^raw$|~$/;

Ignore these names when reading directories:

=over 4

=item *

CVS and RCS directories

=item *

CVS working files

=item *

directory raw for prolog & epilog files

=item *

Editor backup files: emacs: *~

=back

=item $max_errors = number;

Abort after this many errors.

=back

=head1 AUTHOR

Heinz Knutzen <heinzknutzen@users.berlios.de>

=head1 SEE ALSO

http://netspoc.berlios.de

	


