=head1 NAME

netspoc - network security policy compiler

=head1 SYNOPSIS

netspoc [options] input-dir [output-dir]

netspoc [options] input-file [output-dir]

=head1 DESCRIPTION

The network security compiler takes a policy description
recursively from all files in input-dir and places one file for
each managed device into output-dir.
Alternatively input may be read from a single input-file; this
is mainly used for small examples or testing.
Input is read from STDIN if input-file equals "-".
If output-dir is missing, all output is written to STDOUT.

=head1 OPTIONS

The following options are recognized. Most can be negated (prefixed with "no") which
is specially useful when the default is "true".

=over 4

=item --verbose

Controls whether netspoc shows output about different
compiler phases and statistics on standard error.

=item --comment_acls

Add a comment line before each generated ACL entry.
Comments use names of network objects as defined in 
the topology.

=item --comment_routes

Add a comment line before each generated routing entry.
Comments use names of network objects as defined in 
the topology.

=item --allow_unused_groups yes|no|warn

Handling of unused groups and service groups.

=item --strict_subnets yes|no|warn

Allow subnets only if the enclosing network is declared as 'route_hint'
or if the subnet is declared as 'subnet_of'.
If set to 'warn', netspoc only warns about undeclared subnet relations.

=item --auto_default_route

Optimize the number of routing entries per router:

For each router find the hop, where the largest 
number of routing entries points to 
and replace them with a single default route.
This is only applicable for internal networks 
which have no default route to the internet.

=item --ignore_files regex (default: ^CVS$|^RCS$|^.#|^raw$|~$)

A regular expression matching filenames which are ignored when reading
directories.
Default value matches these files:

=over 4

=item *

CVS and RCS directories

=item *

CVS working files

=item *

directory raw for prolog & epilog files

=item *

Editor backup files: emacs: *~

=back

=item --max_errors number

Abort after this many errors.

=back

=head1 AUTHOR

Heinz Knutzen <heinzknutzen@users.berlios.de>

=head1 SEE ALSO

http://netspoc.berlios.de

	


