############################################################
# generated by "huge.pl"
=TITLE=Many nested loops
=INPUT=
network:n1 = { ip = 10.0.1.0/25; }
router:r1a = {
 model = ASA;
 managed;
 interface:n1  = { ip = 10.0.1.1; hardware = n; }
 interface:n1a = { ip = 10.0.1.130; hardware = a; }
}
network:n1a = { ip = 10.0.1.128/30; }
router:r1b = {
 model = ASA;
 managed;
 interface:n1  = { ip = 10.0.1.2; hardware = n; }
 interface:n1b = { ip = 10.0.1.134; hardware = b; }
}
network:n1b = { ip = 10.0.1.132/30; }
service:s1 = {
 user = network:n1;
 permit src = user; dst = network:n100; prt = tcp 80;
}
network:n2 = { ip = 10.0.2.0/25; }
router:r2a = {
 model = ASA;
 managed;
 interface:n2  = { ip = 10.0.2.1; hardware = n; }
 interface:n2a = { ip = 10.0.2.130; hardware = a; }
}
network:n2a = { ip = 10.0.2.128/30; }
router:r2b = {
 model = ASA;
 managed;
 interface:n2  = { ip = 10.0.2.2; hardware = n; }
 interface:n2b = { ip = 10.0.2.134; hardware = b; }
}
network:n2b = { ip = 10.0.2.132/30; }
service:s2 = {
 user = network:n2;
 permit src = user; dst = network:n99; prt = tcp 80;
}
network:n3 = { ip = 10.0.3.0/25; }
router:r3a = {
 model = ASA;
 managed;
 interface:n3  = { ip = 10.0.3.1; hardware = n; }
 interface:n3a = { ip = 10.0.3.130; hardware = a; }
}
network:n3a = { ip = 10.0.3.128/30; }
router:r3b = {
 model = ASA;
 managed;
 interface:n3  = { ip = 10.0.3.2; hardware = n; }
 interface:n3b = { ip = 10.0.3.134; hardware = b; }
}
network:n3b = { ip = 10.0.3.132/30; }
service:s3 = {
 user = network:n3;
 permit src = user; dst = network:n98; prt = tcp 80;
}
network:n4 = { ip = 10.0.4.0/25; }
router:r4a = {
 model = ASA;
 managed;
 interface:n4  = { ip = 10.0.4.1; hardware = n; }
 interface:n4a = { ip = 10.0.4.130; hardware = a; }
}
network:n4a = { ip = 10.0.4.128/30; }
router:r4b = {
 model = ASA;
 managed;
 interface:n4  = { ip = 10.0.4.2; hardware = n; }
 interface:n4b = { ip = 10.0.4.134; hardware = b; }
}
network:n4b = { ip = 10.0.4.132/30; }
service:s4 = {
 user = network:n4;
 permit src = user; dst = network:n97; prt = tcp 80;
}
network:n5 = { ip = 10.0.5.0/25; }
router:r5a = {
 model = ASA;
 managed;
 interface:n5  = { ip = 10.0.5.1; hardware = n; }
 interface:n5a = { ip = 10.0.5.130; hardware = a; }
}
network:n5a = { ip = 10.0.5.128/30; }
router:r5b = {
 model = ASA;
 managed;
 interface:n5  = { ip = 10.0.5.2; hardware = n; }
 interface:n5b = { ip = 10.0.5.134; hardware = b; }
}
network:n5b = { ip = 10.0.5.132/30; }
service:s5 = {
 user = network:n5;
 permit src = user; dst = network:n96; prt = tcp 80;
}
network:n6 = { ip = 10.0.6.0/25; }
router:r6a = {
 model = ASA;
 managed;
 interface:n6  = { ip = 10.0.6.1; hardware = n; }
 interface:n6a = { ip = 10.0.6.130; hardware = a; }
}
network:n6a = { ip = 10.0.6.128/30; }
router:r6b = {
 model = ASA;
 managed;
 interface:n6  = { ip = 10.0.6.2; hardware = n; }
 interface:n6b = { ip = 10.0.6.134; hardware = b; }
}
network:n6b = { ip = 10.0.6.132/30; }
service:s6 = {
 user = network:n6;
 permit src = user; dst = network:n95; prt = tcp 80;
}
network:n7 = { ip = 10.0.7.0/25; }
router:r7a = {
 model = ASA;
 managed;
 interface:n7  = { ip = 10.0.7.1; hardware = n; }
 interface:n7a = { ip = 10.0.7.130; hardware = a; }
}
network:n7a = { ip = 10.0.7.128/30; }
router:r7b = {
 model = ASA;
 managed;
 interface:n7  = { ip = 10.0.7.2; hardware = n; }
 interface:n7b = { ip = 10.0.7.134; hardware = b; }
}
network:n7b = { ip = 10.0.7.132/30; }
service:s7 = {
 user = network:n7;
 permit src = user; dst = network:n94; prt = tcp 80;
}
network:n8 = { ip = 10.0.8.0/25; }
router:r8a = {
 model = ASA;
 managed;
 interface:n8  = { ip = 10.0.8.1; hardware = n; }
 interface:n8a = { ip = 10.0.8.130; hardware = a; }
}
network:n8a = { ip = 10.0.8.128/30; }
router:r8b = {
 model = ASA;
 managed;
 interface:n8  = { ip = 10.0.8.2; hardware = n; }
 interface:n8b = { ip = 10.0.8.134; hardware = b; }
}
network:n8b = { ip = 10.0.8.132/30; }
service:s8 = {
 user = network:n8;
 permit src = user; dst = network:n93; prt = tcp 80;
}
network:n9 = { ip = 10.0.9.0/25; }
router:r9a = {
 model = ASA;
 managed;
 interface:n9  = { ip = 10.0.9.1; hardware = n; }
 interface:n9a = { ip = 10.0.9.130; hardware = a; }
}
network:n9a = { ip = 10.0.9.128/30; }
router:r9b = {
 model = ASA;
 managed;
 interface:n9  = { ip = 10.0.9.2; hardware = n; }
 interface:n9b = { ip = 10.0.9.134; hardware = b; }
}
network:n9b = { ip = 10.0.9.132/30; }
service:s9 = {
 user = network:n9;
 permit src = user; dst = network:n92; prt = tcp 80;
}
network:n10 = { ip = 10.0.10.0/25; }
router:r10a = {
 model = ASA;
 managed;
 interface:n10  = { ip = 10.0.10.1; hardware = n; }
 interface:n10a = { ip = 10.0.10.130; hardware = a; }
}
network:n10a = { ip = 10.0.10.128/30; }
router:r10b = {
 model = ASA;
 managed;
 interface:n10  = { ip = 10.0.10.2; hardware = n; }
 interface:n10b = { ip = 10.0.10.134; hardware = b; }
}
network:n10b = { ip = 10.0.10.132/30; }
service:s10 = {
 user = network:n10;
 permit src = user; dst = network:n91; prt = tcp 80;
}
network:n11 = { ip = 10.0.11.0/25; }
router:r11a = {
 model = ASA;
 managed;
 interface:n11  = { ip = 10.0.11.1; hardware = n; }
 interface:n11a = { ip = 10.0.11.130; hardware = a; }
}
network:n11a = { ip = 10.0.11.128/30; }
router:r11b = {
 model = ASA;
 managed;
 interface:n11  = { ip = 10.0.11.2; hardware = n; }
 interface:n11b = { ip = 10.0.11.134; hardware = b; }
}
network:n11b = { ip = 10.0.11.132/30; }
service:s11 = {
 user = network:n11;
 permit src = user; dst = network:n90; prt = tcp 80;
}
network:n12 = { ip = 10.0.12.0/25; }
router:r12a = {
 model = ASA;
 managed;
 interface:n12  = { ip = 10.0.12.1; hardware = n; }
 interface:n12a = { ip = 10.0.12.130; hardware = a; }
}
network:n12a = { ip = 10.0.12.128/30; }
router:r12b = {
 model = ASA;
 managed;
 interface:n12  = { ip = 10.0.12.2; hardware = n; }
 interface:n12b = { ip = 10.0.12.134; hardware = b; }
}
network:n12b = { ip = 10.0.12.132/30; }
service:s12 = {
 user = network:n12;
 permit src = user; dst = network:n89; prt = tcp 80;
}
network:n13 = { ip = 10.0.13.0/25; }
router:r13a = {
 model = ASA;
 managed;
 interface:n13  = { ip = 10.0.13.1; hardware = n; }
 interface:n13a = { ip = 10.0.13.130; hardware = a; }
}
network:n13a = { ip = 10.0.13.128/30; }
router:r13b = {
 model = ASA;
 managed;
 interface:n13  = { ip = 10.0.13.2; hardware = n; }
 interface:n13b = { ip = 10.0.13.134; hardware = b; }
}
network:n13b = { ip = 10.0.13.132/30; }
service:s13 = {
 user = network:n13;
 permit src = user; dst = network:n88; prt = tcp 80;
}
network:n14 = { ip = 10.0.14.0/25; }
router:r14a = {
 model = ASA;
 managed;
 interface:n14  = { ip = 10.0.14.1; hardware = n; }
 interface:n14a = { ip = 10.0.14.130; hardware = a; }
}
network:n14a = { ip = 10.0.14.128/30; }
router:r14b = {
 model = ASA;
 managed;
 interface:n14  = { ip = 10.0.14.2; hardware = n; }
 interface:n14b = { ip = 10.0.14.134; hardware = b; }
}
network:n14b = { ip = 10.0.14.132/30; }
service:s14 = {
 user = network:n14;
 permit src = user; dst = network:n87; prt = tcp 80;
}
network:n15 = { ip = 10.0.15.0/25; }
router:r15a = {
 model = ASA;
 managed;
 interface:n15  = { ip = 10.0.15.1; hardware = n; }
 interface:n15a = { ip = 10.0.15.130; hardware = a; }
}
network:n15a = { ip = 10.0.15.128/30; }
router:r15b = {
 model = ASA;
 managed;
 interface:n15  = { ip = 10.0.15.2; hardware = n; }
 interface:n15b = { ip = 10.0.15.134; hardware = b; }
}
network:n15b = { ip = 10.0.15.132/30; }
service:s15 = {
 user = network:n15;
 permit src = user; dst = network:n86; prt = tcp 80;
}
network:n16 = { ip = 10.0.16.0/25; }
router:r16a = {
 model = ASA;
 managed;
 interface:n16  = { ip = 10.0.16.1; hardware = n; }
 interface:n16a = { ip = 10.0.16.130; hardware = a; }
}
network:n16a = { ip = 10.0.16.128/30; }
router:r16b = {
 model = ASA;
 managed;
 interface:n16  = { ip = 10.0.16.2; hardware = n; }
 interface:n16b = { ip = 10.0.16.134; hardware = b; }
}
network:n16b = { ip = 10.0.16.132/30; }
service:s16 = {
 user = network:n16;
 permit src = user; dst = network:n85; prt = tcp 80;
}
network:n17 = { ip = 10.0.17.0/25; }
router:r17a = {
 model = ASA;
 managed;
 interface:n17  = { ip = 10.0.17.1; hardware = n; }
 interface:n17a = { ip = 10.0.17.130; hardware = a; }
}
network:n17a = { ip = 10.0.17.128/30; }
router:r17b = {
 model = ASA;
 managed;
 interface:n17  = { ip = 10.0.17.2; hardware = n; }
 interface:n17b = { ip = 10.0.17.134; hardware = b; }
}
network:n17b = { ip = 10.0.17.132/30; }
service:s17 = {
 user = network:n17;
 permit src = user; dst = network:n84; prt = tcp 80;
}
network:n18 = { ip = 10.0.18.0/25; }
router:r18a = {
 model = ASA;
 managed;
 interface:n18  = { ip = 10.0.18.1; hardware = n; }
 interface:n18a = { ip = 10.0.18.130; hardware = a; }
}
network:n18a = { ip = 10.0.18.128/30; }
router:r18b = {
 model = ASA;
 managed;
 interface:n18  = { ip = 10.0.18.2; hardware = n; }
 interface:n18b = { ip = 10.0.18.134; hardware = b; }
}
network:n18b = { ip = 10.0.18.132/30; }
service:s18 = {
 user = network:n18;
 permit src = user; dst = network:n83; prt = tcp 80;
}
network:n19 = { ip = 10.0.19.0/25; }
router:r19a = {
 model = ASA;
 managed;
 interface:n19  = { ip = 10.0.19.1; hardware = n; }
 interface:n19a = { ip = 10.0.19.130; hardware = a; }
}
network:n19a = { ip = 10.0.19.128/30; }
router:r19b = {
 model = ASA;
 managed;
 interface:n19  = { ip = 10.0.19.2; hardware = n; }
 interface:n19b = { ip = 10.0.19.134; hardware = b; }
}
network:n19b = { ip = 10.0.19.132/30; }
service:s19 = {
 user = network:n19;
 permit src = user; dst = network:n82; prt = tcp 80;
}
network:n20 = { ip = 10.0.20.0/25; }
router:r20a = {
 model = ASA;
 managed;
 interface:n20  = { ip = 10.0.20.1; hardware = n; }
 interface:n20a = { ip = 10.0.20.130; hardware = a; }
}
network:n20a = { ip = 10.0.20.128/30; }
router:r20b = {
 model = ASA;
 managed;
 interface:n20  = { ip = 10.0.20.2; hardware = n; }
 interface:n20b = { ip = 10.0.20.134; hardware = b; }
}
network:n20b = { ip = 10.0.20.132/30; }
service:s20 = {
 user = network:n20;
 permit src = user; dst = network:n81; prt = tcp 80;
}
network:n21 = { ip = 10.0.21.0/25; }
router:r21a = {
 model = ASA;
 managed;
 interface:n21  = { ip = 10.0.21.1; hardware = n; }
 interface:n21a = { ip = 10.0.21.130; hardware = a; }
}
network:n21a = { ip = 10.0.21.128/30; }
router:r21b = {
 model = ASA;
 managed;
 interface:n21  = { ip = 10.0.21.2; hardware = n; }
 interface:n21b = { ip = 10.0.21.134; hardware = b; }
}
network:n21b = { ip = 10.0.21.132/30; }
service:s21 = {
 user = network:n21;
 permit src = user; dst = network:n80; prt = tcp 80;
}
network:n22 = { ip = 10.0.22.0/25; }
router:r22a = {
 model = ASA;
 managed;
 interface:n22  = { ip = 10.0.22.1; hardware = n; }
 interface:n22a = { ip = 10.0.22.130; hardware = a; }
}
network:n22a = { ip = 10.0.22.128/30; }
router:r22b = {
 model = ASA;
 managed;
 interface:n22  = { ip = 10.0.22.2; hardware = n; }
 interface:n22b = { ip = 10.0.22.134; hardware = b; }
}
network:n22b = { ip = 10.0.22.132/30; }
service:s22 = {
 user = network:n22;
 permit src = user; dst = network:n79; prt = tcp 80;
}
network:n23 = { ip = 10.0.23.0/25; }
router:r23a = {
 model = ASA;
 managed;
 interface:n23  = { ip = 10.0.23.1; hardware = n; }
 interface:n23a = { ip = 10.0.23.130; hardware = a; }
}
network:n23a = { ip = 10.0.23.128/30; }
router:r23b = {
 model = ASA;
 managed;
 interface:n23  = { ip = 10.0.23.2; hardware = n; }
 interface:n23b = { ip = 10.0.23.134; hardware = b; }
}
network:n23b = { ip = 10.0.23.132/30; }
service:s23 = {
 user = network:n23;
 permit src = user; dst = network:n78; prt = tcp 80;
}
network:n24 = { ip = 10.0.24.0/25; }
router:r24a = {
 model = ASA;
 managed;
 interface:n24  = { ip = 10.0.24.1; hardware = n; }
 interface:n24a = { ip = 10.0.24.130; hardware = a; }
}
network:n24a = { ip = 10.0.24.128/30; }
router:r24b = {
 model = ASA;
 managed;
 interface:n24  = { ip = 10.0.24.2; hardware = n; }
 interface:n24b = { ip = 10.0.24.134; hardware = b; }
}
network:n24b = { ip = 10.0.24.132/30; }
service:s24 = {
 user = network:n24;
 permit src = user; dst = network:n77; prt = tcp 80;
}
network:n25 = { ip = 10.0.25.0/25; }
router:r25a = {
 model = ASA;
 managed;
 interface:n25  = { ip = 10.0.25.1; hardware = n; }
 interface:n25a = { ip = 10.0.25.130; hardware = a; }
}
network:n25a = { ip = 10.0.25.128/30; }
router:r25b = {
 model = ASA;
 managed;
 interface:n25  = { ip = 10.0.25.2; hardware = n; }
 interface:n25b = { ip = 10.0.25.134; hardware = b; }
}
network:n25b = { ip = 10.0.25.132/30; }
service:s25 = {
 user = network:n25;
 permit src = user; dst = network:n76; prt = tcp 80;
}
network:n26 = { ip = 10.0.26.0/25; }
router:r26a = {
 model = ASA;
 managed;
 interface:n26  = { ip = 10.0.26.1; hardware = n; }
 interface:n26a = { ip = 10.0.26.130; hardware = a; }
}
network:n26a = { ip = 10.0.26.128/30; }
router:r26b = {
 model = ASA;
 managed;
 interface:n26  = { ip = 10.0.26.2; hardware = n; }
 interface:n26b = { ip = 10.0.26.134; hardware = b; }
}
network:n26b = { ip = 10.0.26.132/30; }
service:s26 = {
 user = network:n26;
 permit src = user; dst = network:n75; prt = tcp 80;
}
network:n27 = { ip = 10.0.27.0/25; }
router:r27a = {
 model = ASA;
 managed;
 interface:n27  = { ip = 10.0.27.1; hardware = n; }
 interface:n27a = { ip = 10.0.27.130; hardware = a; }
}
network:n27a = { ip = 10.0.27.128/30; }
router:r27b = {
 model = ASA;
 managed;
 interface:n27  = { ip = 10.0.27.2; hardware = n; }
 interface:n27b = { ip = 10.0.27.134; hardware = b; }
}
network:n27b = { ip = 10.0.27.132/30; }
service:s27 = {
 user = network:n27;
 permit src = user; dst = network:n74; prt = tcp 80;
}
network:n28 = { ip = 10.0.28.0/25; }
router:r28a = {
 model = ASA;
 managed;
 interface:n28  = { ip = 10.0.28.1; hardware = n; }
 interface:n28a = { ip = 10.0.28.130; hardware = a; }
}
network:n28a = { ip = 10.0.28.128/30; }
router:r28b = {
 model = ASA;
 managed;
 interface:n28  = { ip = 10.0.28.2; hardware = n; }
 interface:n28b = { ip = 10.0.28.134; hardware = b; }
}
network:n28b = { ip = 10.0.28.132/30; }
service:s28 = {
 user = network:n28;
 permit src = user; dst = network:n73; prt = tcp 80;
}
network:n29 = { ip = 10.0.29.0/25; }
router:r29a = {
 model = ASA;
 managed;
 interface:n29  = { ip = 10.0.29.1; hardware = n; }
 interface:n29a = { ip = 10.0.29.130; hardware = a; }
}
network:n29a = { ip = 10.0.29.128/30; }
router:r29b = {
 model = ASA;
 managed;
 interface:n29  = { ip = 10.0.29.2; hardware = n; }
 interface:n29b = { ip = 10.0.29.134; hardware = b; }
}
network:n29b = { ip = 10.0.29.132/30; }
service:s29 = {
 user = network:n29;
 permit src = user; dst = network:n72; prt = tcp 80;
}
network:n30 = { ip = 10.0.30.0/25; }
router:r30a = {
 model = ASA;
 managed;
 interface:n30  = { ip = 10.0.30.1; hardware = n; }
 interface:n30a = { ip = 10.0.30.130; hardware = a; }
}
network:n30a = { ip = 10.0.30.128/30; }
router:r30b = {
 model = ASA;
 managed;
 interface:n30  = { ip = 10.0.30.2; hardware = n; }
 interface:n30b = { ip = 10.0.30.134; hardware = b; }
}
network:n30b = { ip = 10.0.30.132/30; }
service:s30 = {
 user = network:n30;
 permit src = user; dst = network:n71; prt = tcp 80;
}
network:n31 = { ip = 10.0.31.0/25; }
router:r31a = {
 model = ASA;
 managed;
 interface:n31  = { ip = 10.0.31.1; hardware = n; }
 interface:n31a = { ip = 10.0.31.130; hardware = a; }
}
network:n31a = { ip = 10.0.31.128/30; }
router:r31b = {
 model = ASA;
 managed;
 interface:n31  = { ip = 10.0.31.2; hardware = n; }
 interface:n31b = { ip = 10.0.31.134; hardware = b; }
}
network:n31b = { ip = 10.0.31.132/30; }
service:s31 = {
 user = network:n31;
 permit src = user; dst = network:n70; prt = tcp 80;
}
network:n32 = { ip = 10.0.32.0/25; }
router:r32a = {
 model = ASA;
 managed;
 interface:n32  = { ip = 10.0.32.1; hardware = n; }
 interface:n32a = { ip = 10.0.32.130; hardware = a; }
}
network:n32a = { ip = 10.0.32.128/30; }
router:r32b = {
 model = ASA;
 managed;
 interface:n32  = { ip = 10.0.32.2; hardware = n; }
 interface:n32b = { ip = 10.0.32.134; hardware = b; }
}
network:n32b = { ip = 10.0.32.132/30; }
service:s32 = {
 user = network:n32;
 permit src = user; dst = network:n69; prt = tcp 80;
}
network:n33 = { ip = 10.0.33.0/25; }
router:r33a = {
 model = ASA;
 managed;
 interface:n33  = { ip = 10.0.33.1; hardware = n; }
 interface:n33a = { ip = 10.0.33.130; hardware = a; }
}
network:n33a = { ip = 10.0.33.128/30; }
router:r33b = {
 model = ASA;
 managed;
 interface:n33  = { ip = 10.0.33.2; hardware = n; }
 interface:n33b = { ip = 10.0.33.134; hardware = b; }
}
network:n33b = { ip = 10.0.33.132/30; }
service:s33 = {
 user = network:n33;
 permit src = user; dst = network:n68; prt = tcp 80;
}
network:n34 = { ip = 10.0.34.0/25; }
router:r34a = {
 model = ASA;
 managed;
 interface:n34  = { ip = 10.0.34.1; hardware = n; }
 interface:n34a = { ip = 10.0.34.130; hardware = a; }
}
network:n34a = { ip = 10.0.34.128/30; }
router:r34b = {
 model = ASA;
 managed;
 interface:n34  = { ip = 10.0.34.2; hardware = n; }
 interface:n34b = { ip = 10.0.34.134; hardware = b; }
}
network:n34b = { ip = 10.0.34.132/30; }
service:s34 = {
 user = network:n34;
 permit src = user; dst = network:n67; prt = tcp 80;
}
network:n35 = { ip = 10.0.35.0/25; }
router:r35a = {
 model = ASA;
 managed;
 interface:n35  = { ip = 10.0.35.1; hardware = n; }
 interface:n35a = { ip = 10.0.35.130; hardware = a; }
}
network:n35a = { ip = 10.0.35.128/30; }
router:r35b = {
 model = ASA;
 managed;
 interface:n35  = { ip = 10.0.35.2; hardware = n; }
 interface:n35b = { ip = 10.0.35.134; hardware = b; }
}
network:n35b = { ip = 10.0.35.132/30; }
service:s35 = {
 user = network:n35;
 permit src = user; dst = network:n66; prt = tcp 80;
}
network:n36 = { ip = 10.0.36.0/25; }
router:r36a = {
 model = ASA;
 managed;
 interface:n36  = { ip = 10.0.36.1; hardware = n; }
 interface:n36a = { ip = 10.0.36.130; hardware = a; }
}
network:n36a = { ip = 10.0.36.128/30; }
router:r36b = {
 model = ASA;
 managed;
 interface:n36  = { ip = 10.0.36.2; hardware = n; }
 interface:n36b = { ip = 10.0.36.134; hardware = b; }
}
network:n36b = { ip = 10.0.36.132/30; }
service:s36 = {
 user = network:n36;
 permit src = user; dst = network:n65; prt = tcp 80;
}
network:n37 = { ip = 10.0.37.0/25; }
router:r37a = {
 model = ASA;
 managed;
 interface:n37  = { ip = 10.0.37.1; hardware = n; }
 interface:n37a = { ip = 10.0.37.130; hardware = a; }
}
network:n37a = { ip = 10.0.37.128/30; }
router:r37b = {
 model = ASA;
 managed;
 interface:n37  = { ip = 10.0.37.2; hardware = n; }
 interface:n37b = { ip = 10.0.37.134; hardware = b; }
}
network:n37b = { ip = 10.0.37.132/30; }
service:s37 = {
 user = network:n37;
 permit src = user; dst = network:n64; prt = tcp 80;
}
network:n38 = { ip = 10.0.38.0/25; }
router:r38a = {
 model = ASA;
 managed;
 interface:n38  = { ip = 10.0.38.1; hardware = n; }
 interface:n38a = { ip = 10.0.38.130; hardware = a; }
}
network:n38a = { ip = 10.0.38.128/30; }
router:r38b = {
 model = ASA;
 managed;
 interface:n38  = { ip = 10.0.38.2; hardware = n; }
 interface:n38b = { ip = 10.0.38.134; hardware = b; }
}
network:n38b = { ip = 10.0.38.132/30; }
service:s38 = {
 user = network:n38;
 permit src = user; dst = network:n63; prt = tcp 80;
}
network:n39 = { ip = 10.0.39.0/25; }
router:r39a = {
 model = ASA;
 managed;
 interface:n39  = { ip = 10.0.39.1; hardware = n; }
 interface:n39a = { ip = 10.0.39.130; hardware = a; }
}
network:n39a = { ip = 10.0.39.128/30; }
router:r39b = {
 model = ASA;
 managed;
 interface:n39  = { ip = 10.0.39.2; hardware = n; }
 interface:n39b = { ip = 10.0.39.134; hardware = b; }
}
network:n39b = { ip = 10.0.39.132/30; }
service:s39 = {
 user = network:n39;
 permit src = user; dst = network:n62; prt = tcp 80;
}
network:n40 = { ip = 10.0.40.0/25; }
router:r40a = {
 model = ASA;
 managed;
 interface:n40  = { ip = 10.0.40.1; hardware = n; }
 interface:n40a = { ip = 10.0.40.130; hardware = a; }
}
network:n40a = { ip = 10.0.40.128/30; }
router:r40b = {
 model = ASA;
 managed;
 interface:n40  = { ip = 10.0.40.2; hardware = n; }
 interface:n40b = { ip = 10.0.40.134; hardware = b; }
}
network:n40b = { ip = 10.0.40.132/30; }
service:s40 = {
 user = network:n40;
 permit src = user; dst = network:n61; prt = tcp 80;
}
network:n41 = { ip = 10.0.41.0/25; }
router:r41a = {
 model = ASA;
 managed;
 interface:n41  = { ip = 10.0.41.1; hardware = n; }
 interface:n41a = { ip = 10.0.41.130; hardware = a; }
}
network:n41a = { ip = 10.0.41.128/30; }
router:r41b = {
 model = ASA;
 managed;
 interface:n41  = { ip = 10.0.41.2; hardware = n; }
 interface:n41b = { ip = 10.0.41.134; hardware = b; }
}
network:n41b = { ip = 10.0.41.132/30; }
service:s41 = {
 user = network:n41;
 permit src = user; dst = network:n60; prt = tcp 80;
}
network:n42 = { ip = 10.0.42.0/25; }
router:r42a = {
 model = ASA;
 managed;
 interface:n42  = { ip = 10.0.42.1; hardware = n; }
 interface:n42a = { ip = 10.0.42.130; hardware = a; }
}
network:n42a = { ip = 10.0.42.128/30; }
router:r42b = {
 model = ASA;
 managed;
 interface:n42  = { ip = 10.0.42.2; hardware = n; }
 interface:n42b = { ip = 10.0.42.134; hardware = b; }
}
network:n42b = { ip = 10.0.42.132/30; }
service:s42 = {
 user = network:n42;
 permit src = user; dst = network:n59; prt = tcp 80;
}
network:n43 = { ip = 10.0.43.0/25; }
router:r43a = {
 model = ASA;
 managed;
 interface:n43  = { ip = 10.0.43.1; hardware = n; }
 interface:n43a = { ip = 10.0.43.130; hardware = a; }
}
network:n43a = { ip = 10.0.43.128/30; }
router:r43b = {
 model = ASA;
 managed;
 interface:n43  = { ip = 10.0.43.2; hardware = n; }
 interface:n43b = { ip = 10.0.43.134; hardware = b; }
}
network:n43b = { ip = 10.0.43.132/30; }
service:s43 = {
 user = network:n43;
 permit src = user; dst = network:n58; prt = tcp 80;
}
network:n44 = { ip = 10.0.44.0/25; }
router:r44a = {
 model = ASA;
 managed;
 interface:n44  = { ip = 10.0.44.1; hardware = n; }
 interface:n44a = { ip = 10.0.44.130; hardware = a; }
}
network:n44a = { ip = 10.0.44.128/30; }
router:r44b = {
 model = ASA;
 managed;
 interface:n44  = { ip = 10.0.44.2; hardware = n; }
 interface:n44b = { ip = 10.0.44.134; hardware = b; }
}
network:n44b = { ip = 10.0.44.132/30; }
service:s44 = {
 user = network:n44;
 permit src = user; dst = network:n57; prt = tcp 80;
}
network:n45 = { ip = 10.0.45.0/25; }
router:r45a = {
 model = ASA;
 managed;
 interface:n45  = { ip = 10.0.45.1; hardware = n; }
 interface:n45a = { ip = 10.0.45.130; hardware = a; }
}
network:n45a = { ip = 10.0.45.128/30; }
router:r45b = {
 model = ASA;
 managed;
 interface:n45  = { ip = 10.0.45.2; hardware = n; }
 interface:n45b = { ip = 10.0.45.134; hardware = b; }
}
network:n45b = { ip = 10.0.45.132/30; }
service:s45 = {
 user = network:n45;
 permit src = user; dst = network:n56; prt = tcp 80;
}
network:n46 = { ip = 10.0.46.0/25; }
router:r46a = {
 model = ASA;
 managed;
 interface:n46  = { ip = 10.0.46.1; hardware = n; }
 interface:n46a = { ip = 10.0.46.130; hardware = a; }
}
network:n46a = { ip = 10.0.46.128/30; }
router:r46b = {
 model = ASA;
 managed;
 interface:n46  = { ip = 10.0.46.2; hardware = n; }
 interface:n46b = { ip = 10.0.46.134; hardware = b; }
}
network:n46b = { ip = 10.0.46.132/30; }
service:s46 = {
 user = network:n46;
 permit src = user; dst = network:n55; prt = tcp 80;
}
network:n47 = { ip = 10.0.47.0/25; }
router:r47a = {
 model = ASA;
 managed;
 interface:n47  = { ip = 10.0.47.1; hardware = n; }
 interface:n47a = { ip = 10.0.47.130; hardware = a; }
}
network:n47a = { ip = 10.0.47.128/30; }
router:r47b = {
 model = ASA;
 managed;
 interface:n47  = { ip = 10.0.47.2; hardware = n; }
 interface:n47b = { ip = 10.0.47.134; hardware = b; }
}
network:n47b = { ip = 10.0.47.132/30; }
service:s47 = {
 user = network:n47;
 permit src = user; dst = network:n54; prt = tcp 80;
}
network:n48 = { ip = 10.0.48.0/25; }
router:r48a = {
 model = ASA;
 managed;
 interface:n48  = { ip = 10.0.48.1; hardware = n; }
 interface:n48a = { ip = 10.0.48.130; hardware = a; }
}
network:n48a = { ip = 10.0.48.128/30; }
router:r48b = {
 model = ASA;
 managed;
 interface:n48  = { ip = 10.0.48.2; hardware = n; }
 interface:n48b = { ip = 10.0.48.134; hardware = b; }
}
network:n48b = { ip = 10.0.48.132/30; }
service:s48 = {
 user = network:n48;
 permit src = user; dst = network:n53; prt = tcp 80;
}
network:n49 = { ip = 10.0.49.0/25; }
router:r49a = {
 model = ASA;
 managed;
 interface:n49  = { ip = 10.0.49.1; hardware = n; }
 interface:n49a = { ip = 10.0.49.130; hardware = a; }
}
network:n49a = { ip = 10.0.49.128/30; }
router:r49b = {
 model = ASA;
 managed;
 interface:n49  = { ip = 10.0.49.2; hardware = n; }
 interface:n49b = { ip = 10.0.49.134; hardware = b; }
}
network:n49b = { ip = 10.0.49.132/30; }
service:s49 = {
 user = network:n49;
 permit src = user; dst = network:n52; prt = tcp 80;
}
network:n50 = { ip = 10.0.50.0/25; }
router:r50a = {
 model = ASA;
 managed;
 interface:n50  = { ip = 10.0.50.1; hardware = n; }
 interface:n50a = { ip = 10.0.50.130; hardware = a; }
}
network:n50a = { ip = 10.0.50.128/30; }
router:r50b = {
 model = ASA;
 managed;
 interface:n50  = { ip = 10.0.50.2; hardware = n; }
 interface:n50b = { ip = 10.0.50.134; hardware = b; }
}
network:n50b = { ip = 10.0.50.132/30; }
service:s50 = {
 user = network:n50;
 permit src = user; dst = network:n51; prt = tcp 80;
}
network:n51 = { ip = 10.0.51.0/25; }
router:r51a = {
 model = ASA;
 managed;
 interface:n51  = { ip = 10.0.51.1; hardware = n; }
 interface:n51a = { ip = 10.0.51.130; hardware = a; }
}
network:n51a = { ip = 10.0.51.128/30; }
router:r51b = {
 model = ASA;
 managed;
 interface:n51  = { ip = 10.0.51.2; hardware = n; }
 interface:n51b = { ip = 10.0.51.134; hardware = b; }
}
network:n51b = { ip = 10.0.51.132/30; }
service:s51 = {
 user = network:n51;
 permit src = user; dst = network:n50; prt = tcp 80;
}
network:n52 = { ip = 10.0.52.0/25; }
router:r52a = {
 model = ASA;
 managed;
 interface:n52  = { ip = 10.0.52.1; hardware = n; }
 interface:n52a = { ip = 10.0.52.130; hardware = a; }
}
network:n52a = { ip = 10.0.52.128/30; }
router:r52b = {
 model = ASA;
 managed;
 interface:n52  = { ip = 10.0.52.2; hardware = n; }
 interface:n52b = { ip = 10.0.52.134; hardware = b; }
}
network:n52b = { ip = 10.0.52.132/30; }
service:s52 = {
 user = network:n52;
 permit src = user; dst = network:n49; prt = tcp 80;
}
network:n53 = { ip = 10.0.53.0/25; }
router:r53a = {
 model = ASA;
 managed;
 interface:n53  = { ip = 10.0.53.1; hardware = n; }
 interface:n53a = { ip = 10.0.53.130; hardware = a; }
}
network:n53a = { ip = 10.0.53.128/30; }
router:r53b = {
 model = ASA;
 managed;
 interface:n53  = { ip = 10.0.53.2; hardware = n; }
 interface:n53b = { ip = 10.0.53.134; hardware = b; }
}
network:n53b = { ip = 10.0.53.132/30; }
service:s53 = {
 user = network:n53;
 permit src = user; dst = network:n48; prt = tcp 80;
}
network:n54 = { ip = 10.0.54.0/25; }
router:r54a = {
 model = ASA;
 managed;
 interface:n54  = { ip = 10.0.54.1; hardware = n; }
 interface:n54a = { ip = 10.0.54.130; hardware = a; }
}
network:n54a = { ip = 10.0.54.128/30; }
router:r54b = {
 model = ASA;
 managed;
 interface:n54  = { ip = 10.0.54.2; hardware = n; }
 interface:n54b = { ip = 10.0.54.134; hardware = b; }
}
network:n54b = { ip = 10.0.54.132/30; }
service:s54 = {
 user = network:n54;
 permit src = user; dst = network:n47; prt = tcp 80;
}
network:n55 = { ip = 10.0.55.0/25; }
router:r55a = {
 model = ASA;
 managed;
 interface:n55  = { ip = 10.0.55.1; hardware = n; }
 interface:n55a = { ip = 10.0.55.130; hardware = a; }
}
network:n55a = { ip = 10.0.55.128/30; }
router:r55b = {
 model = ASA;
 managed;
 interface:n55  = { ip = 10.0.55.2; hardware = n; }
 interface:n55b = { ip = 10.0.55.134; hardware = b; }
}
network:n55b = { ip = 10.0.55.132/30; }
service:s55 = {
 user = network:n55;
 permit src = user; dst = network:n46; prt = tcp 80;
}
network:n56 = { ip = 10.0.56.0/25; }
router:r56a = {
 model = ASA;
 managed;
 interface:n56  = { ip = 10.0.56.1; hardware = n; }
 interface:n56a = { ip = 10.0.56.130; hardware = a; }
}
network:n56a = { ip = 10.0.56.128/30; }
router:r56b = {
 model = ASA;
 managed;
 interface:n56  = { ip = 10.0.56.2; hardware = n; }
 interface:n56b = { ip = 10.0.56.134; hardware = b; }
}
network:n56b = { ip = 10.0.56.132/30; }
service:s56 = {
 user = network:n56;
 permit src = user; dst = network:n45; prt = tcp 80;
}
network:n57 = { ip = 10.0.57.0/25; }
router:r57a = {
 model = ASA;
 managed;
 interface:n57  = { ip = 10.0.57.1; hardware = n; }
 interface:n57a = { ip = 10.0.57.130; hardware = a; }
}
network:n57a = { ip = 10.0.57.128/30; }
router:r57b = {
 model = ASA;
 managed;
 interface:n57  = { ip = 10.0.57.2; hardware = n; }
 interface:n57b = { ip = 10.0.57.134; hardware = b; }
}
network:n57b = { ip = 10.0.57.132/30; }
service:s57 = {
 user = network:n57;
 permit src = user; dst = network:n44; prt = tcp 80;
}
network:n58 = { ip = 10.0.58.0/25; }
router:r58a = {
 model = ASA;
 managed;
 interface:n58  = { ip = 10.0.58.1; hardware = n; }
 interface:n58a = { ip = 10.0.58.130; hardware = a; }
}
network:n58a = { ip = 10.0.58.128/30; }
router:r58b = {
 model = ASA;
 managed;
 interface:n58  = { ip = 10.0.58.2; hardware = n; }
 interface:n58b = { ip = 10.0.58.134; hardware = b; }
}
network:n58b = { ip = 10.0.58.132/30; }
service:s58 = {
 user = network:n58;
 permit src = user; dst = network:n43; prt = tcp 80;
}
network:n59 = { ip = 10.0.59.0/25; }
router:r59a = {
 model = ASA;
 managed;
 interface:n59  = { ip = 10.0.59.1; hardware = n; }
 interface:n59a = { ip = 10.0.59.130; hardware = a; }
}
network:n59a = { ip = 10.0.59.128/30; }
router:r59b = {
 model = ASA;
 managed;
 interface:n59  = { ip = 10.0.59.2; hardware = n; }
 interface:n59b = { ip = 10.0.59.134; hardware = b; }
}
network:n59b = { ip = 10.0.59.132/30; }
service:s59 = {
 user = network:n59;
 permit src = user; dst = network:n42; prt = tcp 80;
}
network:n60 = { ip = 10.0.60.0/25; }
router:r60a = {
 model = ASA;
 managed;
 interface:n60  = { ip = 10.0.60.1; hardware = n; }
 interface:n60a = { ip = 10.0.60.130; hardware = a; }
}
network:n60a = { ip = 10.0.60.128/30; }
router:r60b = {
 model = ASA;
 managed;
 interface:n60  = { ip = 10.0.60.2; hardware = n; }
 interface:n60b = { ip = 10.0.60.134; hardware = b; }
}
network:n60b = { ip = 10.0.60.132/30; }
service:s60 = {
 user = network:n60;
 permit src = user; dst = network:n41; prt = tcp 80;
}
network:n61 = { ip = 10.0.61.0/25; }
router:r61a = {
 model = ASA;
 managed;
 interface:n61  = { ip = 10.0.61.1; hardware = n; }
 interface:n61a = { ip = 10.0.61.130; hardware = a; }
}
network:n61a = { ip = 10.0.61.128/30; }
router:r61b = {
 model = ASA;
 managed;
 interface:n61  = { ip = 10.0.61.2; hardware = n; }
 interface:n61b = { ip = 10.0.61.134; hardware = b; }
}
network:n61b = { ip = 10.0.61.132/30; }
service:s61 = {
 user = network:n61;
 permit src = user; dst = network:n40; prt = tcp 80;
}
network:n62 = { ip = 10.0.62.0/25; }
router:r62a = {
 model = ASA;
 managed;
 interface:n62  = { ip = 10.0.62.1; hardware = n; }
 interface:n62a = { ip = 10.0.62.130; hardware = a; }
}
network:n62a = { ip = 10.0.62.128/30; }
router:r62b = {
 model = ASA;
 managed;
 interface:n62  = { ip = 10.0.62.2; hardware = n; }
 interface:n62b = { ip = 10.0.62.134; hardware = b; }
}
network:n62b = { ip = 10.0.62.132/30; }
service:s62 = {
 user = network:n62;
 permit src = user; dst = network:n39; prt = tcp 80;
}
network:n63 = { ip = 10.0.63.0/25; }
router:r63a = {
 model = ASA;
 managed;
 interface:n63  = { ip = 10.0.63.1; hardware = n; }
 interface:n63a = { ip = 10.0.63.130; hardware = a; }
}
network:n63a = { ip = 10.0.63.128/30; }
router:r63b = {
 model = ASA;
 managed;
 interface:n63  = { ip = 10.0.63.2; hardware = n; }
 interface:n63b = { ip = 10.0.63.134; hardware = b; }
}
network:n63b = { ip = 10.0.63.132/30; }
service:s63 = {
 user = network:n63;
 permit src = user; dst = network:n38; prt = tcp 80;
}
network:n64 = { ip = 10.0.64.0/25; }
router:r64a = {
 model = ASA;
 managed;
 interface:n64  = { ip = 10.0.64.1; hardware = n; }
 interface:n64a = { ip = 10.0.64.130; hardware = a; }
}
network:n64a = { ip = 10.0.64.128/30; }
router:r64b = {
 model = ASA;
 managed;
 interface:n64  = { ip = 10.0.64.2; hardware = n; }
 interface:n64b = { ip = 10.0.64.134; hardware = b; }
}
network:n64b = { ip = 10.0.64.132/30; }
service:s64 = {
 user = network:n64;
 permit src = user; dst = network:n37; prt = tcp 80;
}
network:n65 = { ip = 10.0.65.0/25; }
router:r65a = {
 model = ASA;
 managed;
 interface:n65  = { ip = 10.0.65.1; hardware = n; }
 interface:n65a = { ip = 10.0.65.130; hardware = a; }
}
network:n65a = { ip = 10.0.65.128/30; }
router:r65b = {
 model = ASA;
 managed;
 interface:n65  = { ip = 10.0.65.2; hardware = n; }
 interface:n65b = { ip = 10.0.65.134; hardware = b; }
}
network:n65b = { ip = 10.0.65.132/30; }
service:s65 = {
 user = network:n65;
 permit src = user; dst = network:n36; prt = tcp 80;
}
network:n66 = { ip = 10.0.66.0/25; }
router:r66a = {
 model = ASA;
 managed;
 interface:n66  = { ip = 10.0.66.1; hardware = n; }
 interface:n66a = { ip = 10.0.66.130; hardware = a; }
}
network:n66a = { ip = 10.0.66.128/30; }
router:r66b = {
 model = ASA;
 managed;
 interface:n66  = { ip = 10.0.66.2; hardware = n; }
 interface:n66b = { ip = 10.0.66.134; hardware = b; }
}
network:n66b = { ip = 10.0.66.132/30; }
service:s66 = {
 user = network:n66;
 permit src = user; dst = network:n35; prt = tcp 80;
}
network:n67 = { ip = 10.0.67.0/25; }
router:r67a = {
 model = ASA;
 managed;
 interface:n67  = { ip = 10.0.67.1; hardware = n; }
 interface:n67a = { ip = 10.0.67.130; hardware = a; }
}
network:n67a = { ip = 10.0.67.128/30; }
router:r67b = {
 model = ASA;
 managed;
 interface:n67  = { ip = 10.0.67.2; hardware = n; }
 interface:n67b = { ip = 10.0.67.134; hardware = b; }
}
network:n67b = { ip = 10.0.67.132/30; }
service:s67 = {
 user = network:n67;
 permit src = user; dst = network:n34; prt = tcp 80;
}
network:n68 = { ip = 10.0.68.0/25; }
router:r68a = {
 model = ASA;
 managed;
 interface:n68  = { ip = 10.0.68.1; hardware = n; }
 interface:n68a = { ip = 10.0.68.130; hardware = a; }
}
network:n68a = { ip = 10.0.68.128/30; }
router:r68b = {
 model = ASA;
 managed;
 interface:n68  = { ip = 10.0.68.2; hardware = n; }
 interface:n68b = { ip = 10.0.68.134; hardware = b; }
}
network:n68b = { ip = 10.0.68.132/30; }
service:s68 = {
 user = network:n68;
 permit src = user; dst = network:n33; prt = tcp 80;
}
network:n69 = { ip = 10.0.69.0/25; }
router:r69a = {
 model = ASA;
 managed;
 interface:n69  = { ip = 10.0.69.1; hardware = n; }
 interface:n69a = { ip = 10.0.69.130; hardware = a; }
}
network:n69a = { ip = 10.0.69.128/30; }
router:r69b = {
 model = ASA;
 managed;
 interface:n69  = { ip = 10.0.69.2; hardware = n; }
 interface:n69b = { ip = 10.0.69.134; hardware = b; }
}
network:n69b = { ip = 10.0.69.132/30; }
service:s69 = {
 user = network:n69;
 permit src = user; dst = network:n32; prt = tcp 80;
}
network:n70 = { ip = 10.0.70.0/25; }
router:r70a = {
 model = ASA;
 managed;
 interface:n70  = { ip = 10.0.70.1; hardware = n; }
 interface:n70a = { ip = 10.0.70.130; hardware = a; }
}
network:n70a = { ip = 10.0.70.128/30; }
router:r70b = {
 model = ASA;
 managed;
 interface:n70  = { ip = 10.0.70.2; hardware = n; }
 interface:n70b = { ip = 10.0.70.134; hardware = b; }
}
network:n70b = { ip = 10.0.70.132/30; }
service:s70 = {
 user = network:n70;
 permit src = user; dst = network:n31; prt = tcp 80;
}
network:n71 = { ip = 10.0.71.0/25; }
router:r71a = {
 model = ASA;
 managed;
 interface:n71  = { ip = 10.0.71.1; hardware = n; }
 interface:n71a = { ip = 10.0.71.130; hardware = a; }
}
network:n71a = { ip = 10.0.71.128/30; }
router:r71b = {
 model = ASA;
 managed;
 interface:n71  = { ip = 10.0.71.2; hardware = n; }
 interface:n71b = { ip = 10.0.71.134; hardware = b; }
}
network:n71b = { ip = 10.0.71.132/30; }
service:s71 = {
 user = network:n71;
 permit src = user; dst = network:n30; prt = tcp 80;
}
network:n72 = { ip = 10.0.72.0/25; }
router:r72a = {
 model = ASA;
 managed;
 interface:n72  = { ip = 10.0.72.1; hardware = n; }
 interface:n72a = { ip = 10.0.72.130; hardware = a; }
}
network:n72a = { ip = 10.0.72.128/30; }
router:r72b = {
 model = ASA;
 managed;
 interface:n72  = { ip = 10.0.72.2; hardware = n; }
 interface:n72b = { ip = 10.0.72.134; hardware = b; }
}
network:n72b = { ip = 10.0.72.132/30; }
service:s72 = {
 user = network:n72;
 permit src = user; dst = network:n29; prt = tcp 80;
}
network:n73 = { ip = 10.0.73.0/25; }
router:r73a = {
 model = ASA;
 managed;
 interface:n73  = { ip = 10.0.73.1; hardware = n; }
 interface:n73a = { ip = 10.0.73.130; hardware = a; }
}
network:n73a = { ip = 10.0.73.128/30; }
router:r73b = {
 model = ASA;
 managed;
 interface:n73  = { ip = 10.0.73.2; hardware = n; }
 interface:n73b = { ip = 10.0.73.134; hardware = b; }
}
network:n73b = { ip = 10.0.73.132/30; }
service:s73 = {
 user = network:n73;
 permit src = user; dst = network:n28; prt = tcp 80;
}
network:n74 = { ip = 10.0.74.0/25; }
router:r74a = {
 model = ASA;
 managed;
 interface:n74  = { ip = 10.0.74.1; hardware = n; }
 interface:n74a = { ip = 10.0.74.130; hardware = a; }
}
network:n74a = { ip = 10.0.74.128/30; }
router:r74b = {
 model = ASA;
 managed;
 interface:n74  = { ip = 10.0.74.2; hardware = n; }
 interface:n74b = { ip = 10.0.74.134; hardware = b; }
}
network:n74b = { ip = 10.0.74.132/30; }
service:s74 = {
 user = network:n74;
 permit src = user; dst = network:n27; prt = tcp 80;
}
network:n75 = { ip = 10.0.75.0/25; }
router:r75a = {
 model = ASA;
 managed;
 interface:n75  = { ip = 10.0.75.1; hardware = n; }
 interface:n75a = { ip = 10.0.75.130; hardware = a; }
}
network:n75a = { ip = 10.0.75.128/30; }
router:r75b = {
 model = ASA;
 managed;
 interface:n75  = { ip = 10.0.75.2; hardware = n; }
 interface:n75b = { ip = 10.0.75.134; hardware = b; }
}
network:n75b = { ip = 10.0.75.132/30; }
service:s75 = {
 user = network:n75;
 permit src = user; dst = network:n26; prt = tcp 80;
}
network:n76 = { ip = 10.0.76.0/25; }
router:r76a = {
 model = ASA;
 managed;
 interface:n76  = { ip = 10.0.76.1; hardware = n; }
 interface:n76a = { ip = 10.0.76.130; hardware = a; }
}
network:n76a = { ip = 10.0.76.128/30; }
router:r76b = {
 model = ASA;
 managed;
 interface:n76  = { ip = 10.0.76.2; hardware = n; }
 interface:n76b = { ip = 10.0.76.134; hardware = b; }
}
network:n76b = { ip = 10.0.76.132/30; }
service:s76 = {
 user = network:n76;
 permit src = user; dst = network:n25; prt = tcp 80;
}
network:n77 = { ip = 10.0.77.0/25; }
router:r77a = {
 model = ASA;
 managed;
 interface:n77  = { ip = 10.0.77.1; hardware = n; }
 interface:n77a = { ip = 10.0.77.130; hardware = a; }
}
network:n77a = { ip = 10.0.77.128/30; }
router:r77b = {
 model = ASA;
 managed;
 interface:n77  = { ip = 10.0.77.2; hardware = n; }
 interface:n77b = { ip = 10.0.77.134; hardware = b; }
}
network:n77b = { ip = 10.0.77.132/30; }
service:s77 = {
 user = network:n77;
 permit src = user; dst = network:n24; prt = tcp 80;
}
network:n78 = { ip = 10.0.78.0/25; }
router:r78a = {
 model = ASA;
 managed;
 interface:n78  = { ip = 10.0.78.1; hardware = n; }
 interface:n78a = { ip = 10.0.78.130; hardware = a; }
}
network:n78a = { ip = 10.0.78.128/30; }
router:r78b = {
 model = ASA;
 managed;
 interface:n78  = { ip = 10.0.78.2; hardware = n; }
 interface:n78b = { ip = 10.0.78.134; hardware = b; }
}
network:n78b = { ip = 10.0.78.132/30; }
service:s78 = {
 user = network:n78;
 permit src = user; dst = network:n23; prt = tcp 80;
}
network:n79 = { ip = 10.0.79.0/25; }
router:r79a = {
 model = ASA;
 managed;
 interface:n79  = { ip = 10.0.79.1; hardware = n; }
 interface:n79a = { ip = 10.0.79.130; hardware = a; }
}
network:n79a = { ip = 10.0.79.128/30; }
router:r79b = {
 model = ASA;
 managed;
 interface:n79  = { ip = 10.0.79.2; hardware = n; }
 interface:n79b = { ip = 10.0.79.134; hardware = b; }
}
network:n79b = { ip = 10.0.79.132/30; }
service:s79 = {
 user = network:n79;
 permit src = user; dst = network:n22; prt = tcp 80;
}
network:n80 = { ip = 10.0.80.0/25; }
router:r80a = {
 model = ASA;
 managed;
 interface:n80  = { ip = 10.0.80.1; hardware = n; }
 interface:n80a = { ip = 10.0.80.130; hardware = a; }
}
network:n80a = { ip = 10.0.80.128/30; }
router:r80b = {
 model = ASA;
 managed;
 interface:n80  = { ip = 10.0.80.2; hardware = n; }
 interface:n80b = { ip = 10.0.80.134; hardware = b; }
}
network:n80b = { ip = 10.0.80.132/30; }
service:s80 = {
 user = network:n80;
 permit src = user; dst = network:n21; prt = tcp 80;
}
network:n81 = { ip = 10.0.81.0/25; }
router:r81a = {
 model = ASA;
 managed;
 interface:n81  = { ip = 10.0.81.1; hardware = n; }
 interface:n81a = { ip = 10.0.81.130; hardware = a; }
}
network:n81a = { ip = 10.0.81.128/30; }
router:r81b = {
 model = ASA;
 managed;
 interface:n81  = { ip = 10.0.81.2; hardware = n; }
 interface:n81b = { ip = 10.0.81.134; hardware = b; }
}
network:n81b = { ip = 10.0.81.132/30; }
service:s81 = {
 user = network:n81;
 permit src = user; dst = network:n20; prt = tcp 80;
}
network:n82 = { ip = 10.0.82.0/25; }
router:r82a = {
 model = ASA;
 managed;
 interface:n82  = { ip = 10.0.82.1; hardware = n; }
 interface:n82a = { ip = 10.0.82.130; hardware = a; }
}
network:n82a = { ip = 10.0.82.128/30; }
router:r82b = {
 model = ASA;
 managed;
 interface:n82  = { ip = 10.0.82.2; hardware = n; }
 interface:n82b = { ip = 10.0.82.134; hardware = b; }
}
network:n82b = { ip = 10.0.82.132/30; }
service:s82 = {
 user = network:n82;
 permit src = user; dst = network:n19; prt = tcp 80;
}
network:n83 = { ip = 10.0.83.0/25; }
router:r83a = {
 model = ASA;
 managed;
 interface:n83  = { ip = 10.0.83.1; hardware = n; }
 interface:n83a = { ip = 10.0.83.130; hardware = a; }
}
network:n83a = { ip = 10.0.83.128/30; }
router:r83b = {
 model = ASA;
 managed;
 interface:n83  = { ip = 10.0.83.2; hardware = n; }
 interface:n83b = { ip = 10.0.83.134; hardware = b; }
}
network:n83b = { ip = 10.0.83.132/30; }
service:s83 = {
 user = network:n83;
 permit src = user; dst = network:n18; prt = tcp 80;
}
network:n84 = { ip = 10.0.84.0/25; }
router:r84a = {
 model = ASA;
 managed;
 interface:n84  = { ip = 10.0.84.1; hardware = n; }
 interface:n84a = { ip = 10.0.84.130; hardware = a; }
}
network:n84a = { ip = 10.0.84.128/30; }
router:r84b = {
 model = ASA;
 managed;
 interface:n84  = { ip = 10.0.84.2; hardware = n; }
 interface:n84b = { ip = 10.0.84.134; hardware = b; }
}
network:n84b = { ip = 10.0.84.132/30; }
service:s84 = {
 user = network:n84;
 permit src = user; dst = network:n17; prt = tcp 80;
}
network:n85 = { ip = 10.0.85.0/25; }
router:r85a = {
 model = ASA;
 managed;
 interface:n85  = { ip = 10.0.85.1; hardware = n; }
 interface:n85a = { ip = 10.0.85.130; hardware = a; }
}
network:n85a = { ip = 10.0.85.128/30; }
router:r85b = {
 model = ASA;
 managed;
 interface:n85  = { ip = 10.0.85.2; hardware = n; }
 interface:n85b = { ip = 10.0.85.134; hardware = b; }
}
network:n85b = { ip = 10.0.85.132/30; }
service:s85 = {
 user = network:n85;
 permit src = user; dst = network:n16; prt = tcp 80;
}
network:n86 = { ip = 10.0.86.0/25; }
router:r86a = {
 model = ASA;
 managed;
 interface:n86  = { ip = 10.0.86.1; hardware = n; }
 interface:n86a = { ip = 10.0.86.130; hardware = a; }
}
network:n86a = { ip = 10.0.86.128/30; }
router:r86b = {
 model = ASA;
 managed;
 interface:n86  = { ip = 10.0.86.2; hardware = n; }
 interface:n86b = { ip = 10.0.86.134; hardware = b; }
}
network:n86b = { ip = 10.0.86.132/30; }
service:s86 = {
 user = network:n86;
 permit src = user; dst = network:n15; prt = tcp 80;
}
network:n87 = { ip = 10.0.87.0/25; }
router:r87a = {
 model = ASA;
 managed;
 interface:n87  = { ip = 10.0.87.1; hardware = n; }
 interface:n87a = { ip = 10.0.87.130; hardware = a; }
}
network:n87a = { ip = 10.0.87.128/30; }
router:r87b = {
 model = ASA;
 managed;
 interface:n87  = { ip = 10.0.87.2; hardware = n; }
 interface:n87b = { ip = 10.0.87.134; hardware = b; }
}
network:n87b = { ip = 10.0.87.132/30; }
service:s87 = {
 user = network:n87;
 permit src = user; dst = network:n14; prt = tcp 80;
}
network:n88 = { ip = 10.0.88.0/25; }
router:r88a = {
 model = ASA;
 managed;
 interface:n88  = { ip = 10.0.88.1; hardware = n; }
 interface:n88a = { ip = 10.0.88.130; hardware = a; }
}
network:n88a = { ip = 10.0.88.128/30; }
router:r88b = {
 model = ASA;
 managed;
 interface:n88  = { ip = 10.0.88.2; hardware = n; }
 interface:n88b = { ip = 10.0.88.134; hardware = b; }
}
network:n88b = { ip = 10.0.88.132/30; }
service:s88 = {
 user = network:n88;
 permit src = user; dst = network:n13; prt = tcp 80;
}
network:n89 = { ip = 10.0.89.0/25; }
router:r89a = {
 model = ASA;
 managed;
 interface:n89  = { ip = 10.0.89.1; hardware = n; }
 interface:n89a = { ip = 10.0.89.130; hardware = a; }
}
network:n89a = { ip = 10.0.89.128/30; }
router:r89b = {
 model = ASA;
 managed;
 interface:n89  = { ip = 10.0.89.2; hardware = n; }
 interface:n89b = { ip = 10.0.89.134; hardware = b; }
}
network:n89b = { ip = 10.0.89.132/30; }
service:s89 = {
 user = network:n89;
 permit src = user; dst = network:n12; prt = tcp 80;
}
network:n90 = { ip = 10.0.90.0/25; }
router:r90a = {
 model = ASA;
 managed;
 interface:n90  = { ip = 10.0.90.1; hardware = n; }
 interface:n90a = { ip = 10.0.90.130; hardware = a; }
}
network:n90a = { ip = 10.0.90.128/30; }
router:r90b = {
 model = ASA;
 managed;
 interface:n90  = { ip = 10.0.90.2; hardware = n; }
 interface:n90b = { ip = 10.0.90.134; hardware = b; }
}
network:n90b = { ip = 10.0.90.132/30; }
service:s90 = {
 user = network:n90;
 permit src = user; dst = network:n11; prt = tcp 80;
}
network:n91 = { ip = 10.0.91.0/25; }
router:r91a = {
 model = ASA;
 managed;
 interface:n91  = { ip = 10.0.91.1; hardware = n; }
 interface:n91a = { ip = 10.0.91.130; hardware = a; }
}
network:n91a = { ip = 10.0.91.128/30; }
router:r91b = {
 model = ASA;
 managed;
 interface:n91  = { ip = 10.0.91.2; hardware = n; }
 interface:n91b = { ip = 10.0.91.134; hardware = b; }
}
network:n91b = { ip = 10.0.91.132/30; }
service:s91 = {
 user = network:n91;
 permit src = user; dst = network:n10; prt = tcp 80;
}
network:n92 = { ip = 10.0.92.0/25; }
router:r92a = {
 model = ASA;
 managed;
 interface:n92  = { ip = 10.0.92.1; hardware = n; }
 interface:n92a = { ip = 10.0.92.130; hardware = a; }
}
network:n92a = { ip = 10.0.92.128/30; }
router:r92b = {
 model = ASA;
 managed;
 interface:n92  = { ip = 10.0.92.2; hardware = n; }
 interface:n92b = { ip = 10.0.92.134; hardware = b; }
}
network:n92b = { ip = 10.0.92.132/30; }
service:s92 = {
 user = network:n92;
 permit src = user; dst = network:n9; prt = tcp 80;
}
network:n93 = { ip = 10.0.93.0/25; }
router:r93a = {
 model = ASA;
 managed;
 interface:n93  = { ip = 10.0.93.1; hardware = n; }
 interface:n93a = { ip = 10.0.93.130; hardware = a; }
}
network:n93a = { ip = 10.0.93.128/30; }
router:r93b = {
 model = ASA;
 managed;
 interface:n93  = { ip = 10.0.93.2; hardware = n; }
 interface:n93b = { ip = 10.0.93.134; hardware = b; }
}
network:n93b = { ip = 10.0.93.132/30; }
service:s93 = {
 user = network:n93;
 permit src = user; dst = network:n8; prt = tcp 80;
}
network:n94 = { ip = 10.0.94.0/25; }
router:r94a = {
 model = ASA;
 managed;
 interface:n94  = { ip = 10.0.94.1; hardware = n; }
 interface:n94a = { ip = 10.0.94.130; hardware = a; }
}
network:n94a = { ip = 10.0.94.128/30; }
router:r94b = {
 model = ASA;
 managed;
 interface:n94  = { ip = 10.0.94.2; hardware = n; }
 interface:n94b = { ip = 10.0.94.134; hardware = b; }
}
network:n94b = { ip = 10.0.94.132/30; }
service:s94 = {
 user = network:n94;
 permit src = user; dst = network:n7; prt = tcp 80;
}
network:n95 = { ip = 10.0.95.0/25; }
router:r95a = {
 model = ASA;
 managed;
 interface:n95  = { ip = 10.0.95.1; hardware = n; }
 interface:n95a = { ip = 10.0.95.130; hardware = a; }
}
network:n95a = { ip = 10.0.95.128/30; }
router:r95b = {
 model = ASA;
 managed;
 interface:n95  = { ip = 10.0.95.2; hardware = n; }
 interface:n95b = { ip = 10.0.95.134; hardware = b; }
}
network:n95b = { ip = 10.0.95.132/30; }
service:s95 = {
 user = network:n95;
 permit src = user; dst = network:n6; prt = tcp 80;
}
network:n96 = { ip = 10.0.96.0/25; }
router:r96a = {
 model = ASA;
 managed;
 interface:n96  = { ip = 10.0.96.1; hardware = n; }
 interface:n96a = { ip = 10.0.96.130; hardware = a; }
}
network:n96a = { ip = 10.0.96.128/30; }
router:r96b = {
 model = ASA;
 managed;
 interface:n96  = { ip = 10.0.96.2; hardware = n; }
 interface:n96b = { ip = 10.0.96.134; hardware = b; }
}
network:n96b = { ip = 10.0.96.132/30; }
service:s96 = {
 user = network:n96;
 permit src = user; dst = network:n5; prt = tcp 80;
}
network:n97 = { ip = 10.0.97.0/25; }
router:r97a = {
 model = ASA;
 managed;
 interface:n97  = { ip = 10.0.97.1; hardware = n; }
 interface:n97a = { ip = 10.0.97.130; hardware = a; }
}
network:n97a = { ip = 10.0.97.128/30; }
router:r97b = {
 model = ASA;
 managed;
 interface:n97  = { ip = 10.0.97.2; hardware = n; }
 interface:n97b = { ip = 10.0.97.134; hardware = b; }
}
network:n97b = { ip = 10.0.97.132/30; }
service:s97 = {
 user = network:n97;
 permit src = user; dst = network:n4; prt = tcp 80;
}
network:n98 = { ip = 10.0.98.0/25; }
router:r98a = {
 model = ASA;
 managed;
 interface:n98  = { ip = 10.0.98.1; hardware = n; }
 interface:n98a = { ip = 10.0.98.130; hardware = a; }
}
network:n98a = { ip = 10.0.98.128/30; }
router:r98b = {
 model = ASA;
 managed;
 interface:n98  = { ip = 10.0.98.2; hardware = n; }
 interface:n98b = { ip = 10.0.98.134; hardware = b; }
}
network:n98b = { ip = 10.0.98.132/30; }
service:s98 = {
 user = network:n98;
 permit src = user; dst = network:n3; prt = tcp 80;
}
network:n99 = { ip = 10.0.99.0/25; }
router:r99a = {
 model = ASA;
 managed;
 interface:n99  = { ip = 10.0.99.1; hardware = n; }
 interface:n99a = { ip = 10.0.99.130; hardware = a; }
}
network:n99a = { ip = 10.0.99.128/30; }
router:r99b = {
 model = ASA;
 managed;
 interface:n99  = { ip = 10.0.99.2; hardware = n; }
 interface:n99b = { ip = 10.0.99.134; hardware = b; }
}
network:n99b = { ip = 10.0.99.132/30; }
service:s99 = {
 user = network:n99;
 permit src = user; dst = network:n2; prt = tcp 80;
}
network:n100 = { ip = 10.0.100.0/25; }
router:r100a = {
 model = ASA;
 managed;
 interface:n100  = { ip = 10.0.100.1; hardware = n; }
 interface:n100a = { ip = 10.0.100.130; hardware = a; }
}
network:n100a = { ip = 10.0.100.128/30; }
router:r100b = {
 model = ASA;
 managed;
 interface:n100  = { ip = 10.0.100.2; hardware = n; }
 interface:n100b = { ip = 10.0.100.134; hardware = b; }
}
network:n100b = { ip = 10.0.100.132/30; }
service:s100 = {
 user = network:n100;
 permit src = user; dst = network:n1; prt = tcp 80;
}
router:r = {
 interface:n1a = { ip = 10.0.1.129; hardware = a1; }
 interface:n1b = { ip = 10.0.1.133; hardware = b1; }
 interface:n2a = { ip = 10.0.2.129; hardware = a2; }
 interface:n2b = { ip = 10.0.2.133; hardware = b2; }
 interface:n3a = { ip = 10.0.3.129; hardware = a3; }
 interface:n3b = { ip = 10.0.3.133; hardware = b3; }
 interface:n4a = { ip = 10.0.4.129; hardware = a4; }
 interface:n4b = { ip = 10.0.4.133; hardware = b4; }
 interface:n5a = { ip = 10.0.5.129; hardware = a5; }
 interface:n5b = { ip = 10.0.5.133; hardware = b5; }
 interface:n6a = { ip = 10.0.6.129; hardware = a6; }
 interface:n6b = { ip = 10.0.6.133; hardware = b6; }
 interface:n7a = { ip = 10.0.7.129; hardware = a7; }
 interface:n7b = { ip = 10.0.7.133; hardware = b7; }
 interface:n8a = { ip = 10.0.8.129; hardware = a8; }
 interface:n8b = { ip = 10.0.8.133; hardware = b8; }
 interface:n9a = { ip = 10.0.9.129; hardware = a9; }
 interface:n9b = { ip = 10.0.9.133; hardware = b9; }
 interface:n10a = { ip = 10.0.10.129; hardware = a10; }
 interface:n10b = { ip = 10.0.10.133; hardware = b10; }
 interface:n11a = { ip = 10.0.11.129; hardware = a11; }
 interface:n11b = { ip = 10.0.11.133; hardware = b11; }
 interface:n12a = { ip = 10.0.12.129; hardware = a12; }
 interface:n12b = { ip = 10.0.12.133; hardware = b12; }
 interface:n13a = { ip = 10.0.13.129; hardware = a13; }
 interface:n13b = { ip = 10.0.13.133; hardware = b13; }
 interface:n14a = { ip = 10.0.14.129; hardware = a14; }
 interface:n14b = { ip = 10.0.14.133; hardware = b14; }
 interface:n15a = { ip = 10.0.15.129; hardware = a15; }
 interface:n15b = { ip = 10.0.15.133; hardware = b15; }
 interface:n16a = { ip = 10.0.16.129; hardware = a16; }
 interface:n16b = { ip = 10.0.16.133; hardware = b16; }
 interface:n17a = { ip = 10.0.17.129; hardware = a17; }
 interface:n17b = { ip = 10.0.17.133; hardware = b17; }
 interface:n18a = { ip = 10.0.18.129; hardware = a18; }
 interface:n18b = { ip = 10.0.18.133; hardware = b18; }
 interface:n19a = { ip = 10.0.19.129; hardware = a19; }
 interface:n19b = { ip = 10.0.19.133; hardware = b19; }
 interface:n20a = { ip = 10.0.20.129; hardware = a20; }
 interface:n20b = { ip = 10.0.20.133; hardware = b20; }
 interface:n21a = { ip = 10.0.21.129; hardware = a21; }
 interface:n21b = { ip = 10.0.21.133; hardware = b21; }
 interface:n22a = { ip = 10.0.22.129; hardware = a22; }
 interface:n22b = { ip = 10.0.22.133; hardware = b22; }
 interface:n23a = { ip = 10.0.23.129; hardware = a23; }
 interface:n23b = { ip = 10.0.23.133; hardware = b23; }
 interface:n24a = { ip = 10.0.24.129; hardware = a24; }
 interface:n24b = { ip = 10.0.24.133; hardware = b24; }
 interface:n25a = { ip = 10.0.25.129; hardware = a25; }
 interface:n25b = { ip = 10.0.25.133; hardware = b25; }
 interface:n26a = { ip = 10.0.26.129; hardware = a26; }
 interface:n26b = { ip = 10.0.26.133; hardware = b26; }
 interface:n27a = { ip = 10.0.27.129; hardware = a27; }
 interface:n27b = { ip = 10.0.27.133; hardware = b27; }
 interface:n28a = { ip = 10.0.28.129; hardware = a28; }
 interface:n28b = { ip = 10.0.28.133; hardware = b28; }
 interface:n29a = { ip = 10.0.29.129; hardware = a29; }
 interface:n29b = { ip = 10.0.29.133; hardware = b29; }
 interface:n30a = { ip = 10.0.30.129; hardware = a30; }
 interface:n30b = { ip = 10.0.30.133; hardware = b30; }
 interface:n31a = { ip = 10.0.31.129; hardware = a31; }
 interface:n31b = { ip = 10.0.31.133; hardware = b31; }
 interface:n32a = { ip = 10.0.32.129; hardware = a32; }
 interface:n32b = { ip = 10.0.32.133; hardware = b32; }
 interface:n33a = { ip = 10.0.33.129; hardware = a33; }
 interface:n33b = { ip = 10.0.33.133; hardware = b33; }
 interface:n34a = { ip = 10.0.34.129; hardware = a34; }
 interface:n34b = { ip = 10.0.34.133; hardware = b34; }
 interface:n35a = { ip = 10.0.35.129; hardware = a35; }
 interface:n35b = { ip = 10.0.35.133; hardware = b35; }
 interface:n36a = { ip = 10.0.36.129; hardware = a36; }
 interface:n36b = { ip = 10.0.36.133; hardware = b36; }
 interface:n37a = { ip = 10.0.37.129; hardware = a37; }
 interface:n37b = { ip = 10.0.37.133; hardware = b37; }
 interface:n38a = { ip = 10.0.38.129; hardware = a38; }
 interface:n38b = { ip = 10.0.38.133; hardware = b38; }
 interface:n39a = { ip = 10.0.39.129; hardware = a39; }
 interface:n39b = { ip = 10.0.39.133; hardware = b39; }
 interface:n40a = { ip = 10.0.40.129; hardware = a40; }
 interface:n40b = { ip = 10.0.40.133; hardware = b40; }
 interface:n41a = { ip = 10.0.41.129; hardware = a41; }
 interface:n41b = { ip = 10.0.41.133; hardware = b41; }
 interface:n42a = { ip = 10.0.42.129; hardware = a42; }
 interface:n42b = { ip = 10.0.42.133; hardware = b42; }
 interface:n43a = { ip = 10.0.43.129; hardware = a43; }
 interface:n43b = { ip = 10.0.43.133; hardware = b43; }
 interface:n44a = { ip = 10.0.44.129; hardware = a44; }
 interface:n44b = { ip = 10.0.44.133; hardware = b44; }
 interface:n45a = { ip = 10.0.45.129; hardware = a45; }
 interface:n45b = { ip = 10.0.45.133; hardware = b45; }
 interface:n46a = { ip = 10.0.46.129; hardware = a46; }
 interface:n46b = { ip = 10.0.46.133; hardware = b46; }
 interface:n47a = { ip = 10.0.47.129; hardware = a47; }
 interface:n47b = { ip = 10.0.47.133; hardware = b47; }
 interface:n48a = { ip = 10.0.48.129; hardware = a48; }
 interface:n48b = { ip = 10.0.48.133; hardware = b48; }
 interface:n49a = { ip = 10.0.49.129; hardware = a49; }
 interface:n49b = { ip = 10.0.49.133; hardware = b49; }
 interface:n50a = { ip = 10.0.50.129; hardware = a50; }
 interface:n50b = { ip = 10.0.50.133; hardware = b50; }
 interface:n51a = { ip = 10.0.51.129; hardware = a51; }
 interface:n51b = { ip = 10.0.51.133; hardware = b51; }
 interface:n52a = { ip = 10.0.52.129; hardware = a52; }
 interface:n52b = { ip = 10.0.52.133; hardware = b52; }
 interface:n53a = { ip = 10.0.53.129; hardware = a53; }
 interface:n53b = { ip = 10.0.53.133; hardware = b53; }
 interface:n54a = { ip = 10.0.54.129; hardware = a54; }
 interface:n54b = { ip = 10.0.54.133; hardware = b54; }
 interface:n55a = { ip = 10.0.55.129; hardware = a55; }
 interface:n55b = { ip = 10.0.55.133; hardware = b55; }
 interface:n56a = { ip = 10.0.56.129; hardware = a56; }
 interface:n56b = { ip = 10.0.56.133; hardware = b56; }
 interface:n57a = { ip = 10.0.57.129; hardware = a57; }
 interface:n57b = { ip = 10.0.57.133; hardware = b57; }
 interface:n58a = { ip = 10.0.58.129; hardware = a58; }
 interface:n58b = { ip = 10.0.58.133; hardware = b58; }
 interface:n59a = { ip = 10.0.59.129; hardware = a59; }
 interface:n59b = { ip = 10.0.59.133; hardware = b59; }
 interface:n60a = { ip = 10.0.60.129; hardware = a60; }
 interface:n60b = { ip = 10.0.60.133; hardware = b60; }
 interface:n61a = { ip = 10.0.61.129; hardware = a61; }
 interface:n61b = { ip = 10.0.61.133; hardware = b61; }
 interface:n62a = { ip = 10.0.62.129; hardware = a62; }
 interface:n62b = { ip = 10.0.62.133; hardware = b62; }
 interface:n63a = { ip = 10.0.63.129; hardware = a63; }
 interface:n63b = { ip = 10.0.63.133; hardware = b63; }
 interface:n64a = { ip = 10.0.64.129; hardware = a64; }
 interface:n64b = { ip = 10.0.64.133; hardware = b64; }
 interface:n65a = { ip = 10.0.65.129; hardware = a65; }
 interface:n65b = { ip = 10.0.65.133; hardware = b65; }
 interface:n66a = { ip = 10.0.66.129; hardware = a66; }
 interface:n66b = { ip = 10.0.66.133; hardware = b66; }
 interface:n67a = { ip = 10.0.67.129; hardware = a67; }
 interface:n67b = { ip = 10.0.67.133; hardware = b67; }
 interface:n68a = { ip = 10.0.68.129; hardware = a68; }
 interface:n68b = { ip = 10.0.68.133; hardware = b68; }
 interface:n69a = { ip = 10.0.69.129; hardware = a69; }
 interface:n69b = { ip = 10.0.69.133; hardware = b69; }
 interface:n70a = { ip = 10.0.70.129; hardware = a70; }
 interface:n70b = { ip = 10.0.70.133; hardware = b70; }
 interface:n71a = { ip = 10.0.71.129; hardware = a71; }
 interface:n71b = { ip = 10.0.71.133; hardware = b71; }
 interface:n72a = { ip = 10.0.72.129; hardware = a72; }
 interface:n72b = { ip = 10.0.72.133; hardware = b72; }
 interface:n73a = { ip = 10.0.73.129; hardware = a73; }
 interface:n73b = { ip = 10.0.73.133; hardware = b73; }
 interface:n74a = { ip = 10.0.74.129; hardware = a74; }
 interface:n74b = { ip = 10.0.74.133; hardware = b74; }
 interface:n75a = { ip = 10.0.75.129; hardware = a75; }
 interface:n75b = { ip = 10.0.75.133; hardware = b75; }
 interface:n76a = { ip = 10.0.76.129; hardware = a76; }
 interface:n76b = { ip = 10.0.76.133; hardware = b76; }
 interface:n77a = { ip = 10.0.77.129; hardware = a77; }
 interface:n77b = { ip = 10.0.77.133; hardware = b77; }
 interface:n78a = { ip = 10.0.78.129; hardware = a78; }
 interface:n78b = { ip = 10.0.78.133; hardware = b78; }
 interface:n79a = { ip = 10.0.79.129; hardware = a79; }
 interface:n79b = { ip = 10.0.79.133; hardware = b79; }
 interface:n80a = { ip = 10.0.80.129; hardware = a80; }
 interface:n80b = { ip = 10.0.80.133; hardware = b80; }
 interface:n81a = { ip = 10.0.81.129; hardware = a81; }
 interface:n81b = { ip = 10.0.81.133; hardware = b81; }
 interface:n82a = { ip = 10.0.82.129; hardware = a82; }
 interface:n82b = { ip = 10.0.82.133; hardware = b82; }
 interface:n83a = { ip = 10.0.83.129; hardware = a83; }
 interface:n83b = { ip = 10.0.83.133; hardware = b83; }
 interface:n84a = { ip = 10.0.84.129; hardware = a84; }
 interface:n84b = { ip = 10.0.84.133; hardware = b84; }
 interface:n85a = { ip = 10.0.85.129; hardware = a85; }
 interface:n85b = { ip = 10.0.85.133; hardware = b85; }
 interface:n86a = { ip = 10.0.86.129; hardware = a86; }
 interface:n86b = { ip = 10.0.86.133; hardware = b86; }
 interface:n87a = { ip = 10.0.87.129; hardware = a87; }
 interface:n87b = { ip = 10.0.87.133; hardware = b87; }
 interface:n88a = { ip = 10.0.88.129; hardware = a88; }
 interface:n88b = { ip = 10.0.88.133; hardware = b88; }
 interface:n89a = { ip = 10.0.89.129; hardware = a89; }
 interface:n89b = { ip = 10.0.89.133; hardware = b89; }
 interface:n90a = { ip = 10.0.90.129; hardware = a90; }
 interface:n90b = { ip = 10.0.90.133; hardware = b90; }
 interface:n91a = { ip = 10.0.91.129; hardware = a91; }
 interface:n91b = { ip = 10.0.91.133; hardware = b91; }
 interface:n92a = { ip = 10.0.92.129; hardware = a92; }
 interface:n92b = { ip = 10.0.92.133; hardware = b92; }
 interface:n93a = { ip = 10.0.93.129; hardware = a93; }
 interface:n93b = { ip = 10.0.93.133; hardware = b93; }
 interface:n94a = { ip = 10.0.94.129; hardware = a94; }
 interface:n94b = { ip = 10.0.94.133; hardware = b94; }
 interface:n95a = { ip = 10.0.95.129; hardware = a95; }
 interface:n95b = { ip = 10.0.95.133; hardware = b95; }
 interface:n96a = { ip = 10.0.96.129; hardware = a96; }
 interface:n96b = { ip = 10.0.96.133; hardware = b96; }
 interface:n97a = { ip = 10.0.97.129; hardware = a97; }
 interface:n97b = { ip = 10.0.97.133; hardware = b97; }
 interface:n98a = { ip = 10.0.98.129; hardware = a98; }
 interface:n98b = { ip = 10.0.98.133; hardware = b98; }
 interface:n99a = { ip = 10.0.99.129; hardware = a99; }
 interface:n99b = { ip = 10.0.99.133; hardware = b99; }
 interface:n100a = { ip = 10.0.100.129; hardware = a100; }
 interface:n100b = { ip = 10.0.100.133; hardware = b100; }

}
# Should only try 2 direct paths to dst and not all other loops.
service:s-hub = {
 user = interface:r.n1a;
 permit src = user; dst = network:n1; prt = tcp 81;
}

=END=
=OUTPUT=
--r1a
! [ Routing ]
route a 10.0.100.0 255.255.255.128 10.0.1.129
--
! n_in
access-list n_in extended permit tcp 10.0.1.0 255.255.255.128 10.0.100.0 255.255.255.128 eq 80
access-list n_in extended deny ip any4 any4
access-group n_in in interface n
--
! a_in
access-list a_in extended permit tcp host 10.0.1.129 10.0.1.0 255.255.255.128 eq 81
access-list a_in extended permit tcp 10.0.100.0 255.255.255.128 10.0.1.0 255.255.255.128 eq 80
access-list a_in extended deny ip any4 any4
access-group a_in in interface a
=END=

############################################################
