############################################################
=TITLE=Warn on empty files
=PARAMS=--ipv6
=INPUT=
--ipv6/empty
# Only comment
# network:n1 = { ip = ::a01:100/120; }
--ipv6/valid
# Generated by xyz; DO NOT EDIT.
# :-)
#
--ipv6/topo
network:n1 = { ip = ::a01:100/120; }
-- ipv6/dir/other

=WARNING=
Warning: Ignoring file 'ipv6/dir/other' without any content
Warning: Ignoring file 'ipv6/empty' without any content
=END=

############################################################
=TITLE=Invalid IP address
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100o/24; }
=END=
=ERROR=
Error: Invalid CIDR address: ::a01:100o/24 in 'ip' of network:n1
=END=

############################################################
=TITLE=Invalid IP in anonymous aggregate
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; }
router:r = {
 managed;
 model = IOS;
 interface:n1 = { ip = ::a01:101; hardware = n1; }
}
service:s1 = {
 user = any:[ ip = ::a01:0 & network:n1];
 permit src = user; dst = interface:r.n1; prt = tcp 22;
}
=END=
=ERROR=
Error: Invalid CIDR address: ::a01:0 in any:[ip = ...] of user of service:s1
=END=

############################################################
=TITLE=IP and prefix don't match in anonymous aggregate
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; }
router:r = {
 managed;
 model = IOS;
 interface:n1 = { ip = ::a01:101; hardware = n1; }
}
service:s1 = {
 user = any:[ ip = ::a01:100/112 & network:n1];
 permit src = user; dst = interface:r.n1; prt = tcp 22;
}
=END=
=ERROR=
Error: IP and mask don't match in any:[ip = ...] of user of service:s1
=END=

############################################################
=TITLE=Unknown model for managed router
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 model = foo;
 interface:N = { ip = ::a01:101; hardware = e0; }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unknown model in router:R: foo
=END=

############################################################
=TITLE=Missing model for managed router
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 interface:N = { ip = ::a01:101; hardware = e0; }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Missing 'model' for managed router:R
=END=

############################################################
=TITLE=Unknown extension for model ASA
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 model = ASA, foo, bar;
 interface:N = { ip = ::a01:101; hardware = e0; }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unknown extension in 'model' of router:R: foo
Error: Unknown extension in 'model' of router:R: bar
=END=

############################################################
=TITLE=Unknown extension for model IOS
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 model = IOS, VPN;
 interface:N = { ip = ::a01:101; hardware = e0; }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unknown extension in 'model' of router:R: VPN
=END=

############################################################
=TITLE=Unknown extension for model Linux
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 model = Linux, xyz;
 interface:N = { ip = ::a01:101; hardware = e0; }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unknown extension in 'model' of router:R: xyz
=END=

############################################################
=TITLE=Unexpected attribute no_check
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 model = IOS;
 interface:N = { ip = ::a01:101; hardware = e0; no_check; }
}
network:N = { ip = ::a01:100/120; }
=END=
=WARNING=
Warning: Ignoring attribute 'no_check' at interface:R.N
=END=

############################################################
=TITLE=Unknown attribute in router
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 model = ASA;
 xyz;
 interface:N = { ip = ::a01:101; hardware = e0; }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unexpected attribute in router:R: xyz
=END=

############################################################
=TITLE=Unknown typed name in router
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 model = ASA;
 interface:N = { ip = ::a01:101; hardware = e0; }
 x:y;
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unexpected attribute in router:R: x:y
=END=

############################################################
=TITLE=Invalid hardware name with comment character
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 model = ASA;
 interface:N = { ip = ::a01:101; hardware = e0#3; }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Expected ';' at line 5 of INPUT, near "--HERE-->}"
Aborted
=END=

############################################################
=TITLE=Missing hardware at interface
# Processing of attribute 'no_in_acl' internally uses value of
# hardware.
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 model = ASA;
 interface:N = { ip = ::a01:101; no_in_acl; }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Missing 'hardware' for interface:R.N
=END=

############################################################
=TITLE=Model doesn't support no_in_acl
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 model = Linux;
 interface:N = { ip = ::a01:101; no_in_acl; hardware = N; }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: router:R doesn't support outgoing ACL
=END=

############################################################
=TITLE=Multiple interfaces with attribute 'no_in_acl'
=PARAMS=--ipv6
=INPUT=
network:N1 = { ip = ::a01:100/120; }
network:N2 = { ip = ::a01:200/120; }
router:R = {
 managed;
 model = ASA;
 interface:N1 = { ip = ::a01:101; no_in_acl; hardware = n1; }
 interface:N2 = { ip = ::a01:201; no_in_acl; hardware = n2; }
}
=END=
=ERROR=
Error: At most one interface of router:R may use flag 'no_in_acl'
=END=

############################################################
=TITLE=Multiple interfaces with 'no_in_acl' at one hardware
=PARAMS=--ipv6
=INPUT=
network:N1 = { ip = ::a01:100/120; }
network:N2 = { ip = ::a01:200/120; }
router:R = {
 managed;
 model = ASA;
 interface:N1 = { ip = ::a01:101; no_in_acl; hardware = x; }
 interface:N2 = { ip = ::a01:201; no_in_acl; hardware = x; }
}
=END=
=ERROR=
Error: Only one logical interface allowed at hardware 'x' of router:R
 because of attribute 'no_in_acl'
=END=

############################################################
=TITLE=Unexpected attribute at interface
=PARAMS=--ipv6
=INPUT=
router:R = {
 interface:N = { ip = ::a01:101; foo }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Expected '=' at line 2 of INPUT, near "foo --HERE-->}"
Aborted
=END=

############################################################
=TITLE=Bad typed name as attribute of interface
=PARAMS=--ipv6
=INPUT=
router:R = {
 interface:N = { ip = ::a01:101; primary:p = {} }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unexpected attribute in interface:R.N: primary:p
=END=

############################################################
=TITLE=Short interface at managed router
=PARAMS=--ipv6
=INPUT=
router:R = {
 managed;
 model = ASA;
 interface:N = { hardware = inside; }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Short definition of interface:R.N not allowed
=END=

############################################################
=TITLE=Secondary interface without IP
=PARAMS=--ipv6
=INPUT=
router:R = {
 interface:N = { ip = ::a01:101; secondary:second = {} }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Missing IP in secondary:second of interface:R.N
=END=

############################################################
=TITLE=Secondary interface with bad attribute
=PARAMS=--ipv6
=INPUT=
router:R = {
 interface:N = { ip = ::a01:101; secondary:second = { foo; } }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unexpected attribute in secondary:second of interface:R.N: foo
Error: Missing IP in secondary:second of interface:R.N
=END=

############################################################
=TITLE=Unnumbered with secondary interface
=PARAMS=--ipv6
=INPUT=
router:R = {
 interface:N = { unnumbered; secondary:second = { ip = ::a01:101; } }
}
network:N = { unnumbered; }
=END=
=ERROR=
Error: interface:R.N without IP address must not have secondary address
=END=

############################################################
=TITLE=Negotiated with secondary interface
=PARAMS=--ipv6
=INPUT=
router:R = {
 interface:N = { negotiated; secondary:second = { ip = ::a01:101; } }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: interface:R.N without IP address must not have secondary address
=END=

############################################################
=TITLE=Single secondary interface
=PARAMS=--ipv6
=INPUT=
router:R = {
 interface:N = { secondary:second = { ip = ::a01:101; } }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: interface:R.N without IP address must not have secondary address
=END=

############################################################
=TITLE=Virtual interface with bad attribute
=PARAMS=--ipv6
=INPUT=
router:R = {
 interface:N = { ip = ::a01:101; virtual = { foo; } }
}
network:N = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unexpected attribute in 'virtual' of interface:R.N: foo
Error: Missing IP in 'virtual' of interface:R.N
=END=

############################################################
=TITLE=Typed name expected
=PARAMS=--ipv6
=INPUT=
network = {
=END=
=ERROR=
Error: Typed name expected at line 1 of INPUT, near "--HERE-->network"
Aborted
=END=

############################################################
=TITLE=Unknown global definition
=PARAMS=--ipv6
=INPUT=
networkX:n1 = {
=END=
=ERROR=
Error: Unknown global definition at line 1 of INPUT, near "--HERE-->networkX:n1"
Aborted
=END=

############################################################
=TITLE=Missing '}' after network definition
=PARAMS=--ipv6
=INPUT=
network:n1 = {
 ip = ::a01:100/120;
 host:h1 = { ::a01:10a; }
 FOO = BAR;
network:n2 = { ip = ::a01:200/120; }
network:n3 = { ip = ::a01:300/120; }
=END=
=ERROR=
Error: Expected '}' at line 5 of INPUT, near "--HERE-->network:n2"
Aborted
=END=

############################################################
=TITLE=Missing '}' after owner definition
=PARAMS=--ipv6
=INPUT=
owner:o1 = {
 admins = a1@b.c;
owner:o2 = { admins = a2@b.c; }
=END=
=ERROR=
Error: Expected '}' at line 3 of INPUT, near "--HERE-->owner:o2"
Aborted
=END=

############################################################
=TITLE=Unexpected definition after missing ';' in list
=PARAMS=--ipv6
=INPUT=
group:g1 =
 host:h1,
 host:h2,
network:n2 = { ip = ::a01:200/120; }
network:n3 = { ip = ::a01:300/120; }
=END=
=ERROR=
Error: Expected ';' at line 4 of INPUT, near "network:n2 --HERE-->= { ip"
Aborted
=END=

############################################################
=TITLE=Invalid character in network name
=PARAMS=--ipv6
=INPUT=
network:n1@vrf123 = {}
=END=
=ERROR=
Error: Invalid identifier in definition of 'network:n1@vrf123'
Error: Missing IP address for network:n1@vrf123
=END=

############################################################
=TITLE=Invalid character in router name
=PARAMS=--ipv6
=INPUT=
router:r1/bridged-part = {}
=END=
=ERROR=
Error: Invalid identifier in definition of 'router:r1/bridged-part'
=END=

############################################################
=TITLE=Invalid character in area name
=PARAMS=--ipv6
=INPUT=
area:a1@vrf123 = {}
=END=
=ERROR=
Error: Invalid identifier in definition of 'area.a1@vrf123'
Error: At least one of attributes 'border', 'inclusive_border' or 'anchor' must be defined for area:a1@vrf123
=END=

############################################################
=TITLE=Unexpected end of file
=PARAMS=--ipv6
=INPUT=
network:n1
=END=
=ERROR=
Error: Expected '=' at line 1 of INPUT, at EOF
Aborted
=END=

############################################################
=TITLE=Identifier expected  at EOF
=PARAMS=--ipv6
=INPUT=
network:n1 = { owner =
=END=
=ERROR=
Error: Expected something at line 1 of INPUT, at EOF
Aborted
=END=

############################################################
=TITLE=Identifier expected
=PARAMS=--ipv6
=INPUT=
network:n1 = { owner = }
=END=
=ERROR=
Error: Unexpected separator '}' at line 1 of INPUT, near "owner = --HERE-->}"
Aborted
=END=

############################################################
=TITLE=Invalid identifier in reference
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; owner = a/b; }
=END=
=WARNING=
Warning: Ignoring undefined owner:a/b of network:n1
=END=

############################################################
=TITLE=Invalid identifier in partition
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; partition = a/b; }
=END=
=ERROR=
Error: Invalid identifier in 'partition' of network:n1: a/b
=END=

############################################################
=TITLE=String expected
=PARAMS=--ipv6
=INPUT=
owner:o1 = { admins = ; }
network:n1 = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: List of values expected in 'admins' of owner:o1
=END=

############################################################
=TITLE=Single value expected
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120, ::a01:200/120; }
=END=
=ERROR=
Error: Single value expected in 'ip' of network:n1
Error: Invalid CIDR address:  in 'ip' of network:n1
=END=

############################################################
=TITLE=Structured value expected
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; host:h = ::a01:10a; }
=END=
=ERROR=
Error: Structured value expected in 'host:h'
Error: host:h needs exactly one of attributes 'ip' and 'range'
=END=

############################################################
=TITLE=No value expected
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; has_subnets = yes; }
=END=
=ERROR=
Error: No value expected for flag 'has_subnets' of network:n1
=END=

############################################################
=TITLE=Comma expected in union of values (1)
=PARAMS=--ipv6
=INPUT=
group:g1 = host:h1 host:h2;
=END=
=ERROR=
Error: Expected ';' at line 1 of INPUT, near "host:h1 --HERE-->host:h2"
Aborted
=END=

############################################################
=TITLE=Comma expected in list of values (2)
=PARAMS=--ipv6
=INPUT=
owner:o = { admins = a@b.c x@y.z; }
=END=
=ERROR=
Error: Expected ';' at line 1 of INPUT, near "a@b.c --HERE-->x@y.z"
Aborted
=END=

############################################################
=TITLE=Typed name expected
=PARAMS=--ipv6
=INPUT=
group:g1 = host;
=END=
=ERROR=
Error: Typed name expected at line 1 of INPUT, near "group:g1 = --HERE-->host"
Aborted
=END=

############################################################
=TITLE=Bad hostname in definition
=PARAMS=--ipv6
=INPUT=
network:n1 = {
 ip = ::a01:100/120;
 host:id: = { ip = ::a01:10a; }
 host:@h11 = { ip = ::a01:10b; }
}
=END=
=ERROR=
Error: Invalid name in definition of 'host:id:'
Error: Invalid identifier in definition of 'host:@h11'
=END=

############################################################
=TITLE=Bad hostname in reference
=PARAMS=--ipv6
=INPUT=
service:s1 = {
 user = network:n1, host:id:;
 permit src = user; dst = user; prt = ip;
}
network:n1 = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Can't resolve host:id: in user of service:s1
=END=

############################################################
=TITLE=Bad network name in definition
=PARAMS=--ipv6
=INPUT=
network:n1@vrf = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Invalid identifier in definition of 'network:n1@vrf'
=END=

############################################################
=TITLE=Bad network name in reference
=PARAMS=--ipv6
=INPUT=
service:s1 = {
 user = network:n1, network:n1@vrf:;
 permit src = user; dst = user; prt = ip;
}
network:n1 = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Can't resolve network:n1@vrf: in user of service:s1
=END=

############################################################
=TITLE=Empty interface name
=PARAMS=--ipv6
=INPUT=
group:g1 = interface:;
=END=
=ERROR=
Error: Interface name expected at line 1 of INPUT, near "group:g1 = --HERE-->interface:"
Aborted
=END=

############################################################
=TITLE=Bad interface name
=PARAMS=--ipv6
=INPUT=
group:g1 = interface:r;
=END=
=ERROR=
Error: Interface name expected at line 1 of INPUT, near "group:g1 = --HERE-->interface:r"
Aborted
=END=

############################################################
=TITLE=Invalid interface names
=PARAMS=--ipv6
=INPUT=
service:s1 = {
 user = network:n1, interface:r1., interface:r1.n1@vrf2, interface:r.n.123.nn;
 permit src = user; dst = user; prt = ip;
}
network:n1 = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Can't resolve interface:r1. in user of service:s1
Error: Can't resolve interface:r1.n1@vrf2 in user of service:s1
Error: Can't resolve interface:r.n.123.nn in user of service:s1
=END=

############################################################
=TITLE=Missing [any|all]
=PARAMS=--ipv6
=INPUT=
group:g1 = interface:r1.[ ;
=END=
=ERROR=
Error: Expected [auto|all] at line 1 of INPUT, near "interface:r1.[ --HERE-->;"
Aborted
=END=

############################################################
=TITLE=Bad auto interface
=PARAMS=--ipv6
=INPUT=
group:g1 = interface:r.[foo];
=END=
=ERROR=
Error: Expected [auto|all] at line 1 of INPUT, near "interface:r.[--HERE-->foo]"
Aborted
=END=

############################################################
=TITLE=Unexpected network name in interfaces of network
=PARAMS=--ipv6
=INPUT=
group:g1 = interface:[network:n1].n2;
=END=
=ERROR=
Error: Expected '.[' at line 1 of INPUT, near "interface:[network:n1]--HERE-->.n2"
Aborted
=END=

############################################################
=TITLE=Bad group name in definition
=PARAMS=--ipv6
=INPUT=
group:a@b = ;
=END=
=ERROR=
Error: Invalid identifier in definition of 'group.a@b'
=END=

############################################################
=TITLE=Bad NAT name
=PARAMS=--ipv6
=INPUT=
network:n = { nat:a+b = { ip = ::a09:900/120; } ip = ::a01:100/120; }
=END=
=ERROR=
Error: Expected '=' at line 1 of INPUT, near "nat:a--HERE-->+b"
Aborted
=END=

############################################################
=TITLE=Bad crypto in hub
=PARAMS=--ipv6
=INPUT=
network:n = { ip = ::a01:100/120; }
router:r = {
 managed;
 model = IOS;
 interface:n = { ip = ::a01:101; hardware = n; hub = foo, tool:bar; }
}
=ERROR=
Error: Expected type 'crypto:' in 'hub' of interface:r.n
Error: Expected type 'crypto:' in 'hub' of interface:r.n
=END=

############################################################
=TITLE=Bad crypto in spoke
=PARAMS=--ipv6
=INPUT=
network:n = { ip = ::a01:100/120; }
router:r = {
 managed;
 model = IOS;
 interface:n = { ip = ::a01:101; hardware = n; spoke = cyrpto:n; }
}
=ERROR=
Error: Expected type 'crypto:' in 'spoke' of interface:r.n
=END=

############################################################
=TITLE=Bad VPN id
=PARAMS=--ipv6
=INPUT=
router:r = {
 interface:n1 = { id = a.b.c; }
}
network:n1 = { unnumbered; }
=END=
=ERROR=
Error: Invalid 'id' in interface:r.n1: a.b.c
Error: Attribute 'id' is only valid with 'spoke' at interface:r.n1
=END=

############################################################
=TITLE=Ignore cert_id
=PARAMS=--ipv6
=INPUT=
network:n = { ip = ::a01:100/120; cert_id = a.b.c; }
=END=
=WARNING=
Warning: Ignoring 'cert_id' at network:n
=END=

############################################################
=TITLE=Missing cert_id
=PARAMS=--ipv6
=INPUT=
network:n = {
 ip = ::a01:100/120;
 host:h = { range = ::a01:108 - ::a01:10f; ldap_id = a@b.c; }
}
=END=
=ERROR=
Error: Missing attribute 'cert_id' at network:n having hosts with attribute 'ldap_id'
=END=

############################################################
=TITLE=Bad cert_id
=PARAMS=--ipv6
=INPUT=
network:n = {
 ip = ::a01:100/120; cert_id = @b.c;
 host:h = { ip = ::a01:101; ldap_id = a@b.c; }
}
=END=
=ERROR=
Error: Attribute 'ldap_Id' must only be used together with IP range at host:h
Error: Domain name expected in attribute 'cert_id' of network:n
=END=

############################################################
=TITLE=Bad managed attribute
=PARAMS=--ipv6
=INPUT=
router:r = {
 managed xxx;
 interface:n;
}
network:n = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Expected '=' at line 2 of INPUT, near "managed --HERE-->xxx"
Aborted
=END=

############################################################
=TITLE=Unexpected managed type
=PARAMS=--ipv6
=INPUT=
router:r = {
 managed = xxx;
 interface:n;
}
network:n = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Invalid value for 'managed' of router:r: xxx
=END=

############################################################
=TITLE=Empty value at managed attribute
=PARAMS=--ipv6
=INPUT=
router:r = {
 managed = ;
 interface:n;
}
network:n = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Single value expected in 'managed' of router:r
=END=

############################################################
=TITLE=Unknown routing protocol
=PARAMS=--ipv6
=INPUT=
router:r = {
 routing = xyz;
 interface:n = { routing = abc; }
}
network:n = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unknown routing protocol in 'routing' of router:r
Error: Unknown routing protocol in 'routing' of interface:r.n
=END=

############################################################
=TITLE=Must not use 'routing = manual' at interface
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; }
router:r1 = {
 managed;
 model = ASA;
 interface:n1 = { ip = ::a01:101; hardware = n1; routing = manual; }
}
=END=
=WARNING=
Warning: 'routing=manual' must only be applied to router, not to interface:r1.n1
=END=

############################################################
=TITLE=Bad typed name as attribute of host
=PARAMS=--ipv6
=INPUT=
network:n = {
 ip = ::a01:100/120;
 host:h = { ip = ::a01:101; xy:z; }
}
=END=
=ERROR=
Error: Unexpected attribute in host:h: xy:z
=END=

############################################################
=TITLE=Bad token as attribute of host
=PARAMS=--ipv6
=INPUT=
network:n = {
 host:h = { ip = ::a01:101; ; }
}
=END=
=ERROR=
Error: Unexpected separator ';' at line 2 of INPUT, near "::a01:101; --HERE-->; }"
Aborted
=END=

############################################################
=TITLE=Bad typed name as attribute of network
=PARAMS=--ipv6
=INPUT=
network:n = { xy:z; }
=END=
=ERROR=
Error: Unexpected attribute in network:n: xy:z
Error: Missing IP address for network:n
=END=

############################################################
=TITLE=Bad token as attribute of network
=PARAMS=--ipv6
=INPUT=
network:n = { ; }
=END=
=ERROR=
Error: Unexpected separator ';' at line 1 of INPUT, near "network:n = { --HERE-->; }"
Aborted
=END=

############################################################
=TITLE=Network and host without IP
=PARAMS=--ipv6
=INPUT=
network:n = { host:h1 = {} }
=END=
=ERROR=
Error: host:h1 needs exactly one of attributes 'ip' and 'range'
Error: Missing IP address for network:n
=END=

############################################################
=TITLE=Duplicate IP in network
=PARAMS=--ipv6
=INPUT=
network:n = { ip = ::a01:100/120; unnumbered; ip = ::a01:200/120; }
=END=
=ERROR=
Error: Duplicate attribute 'ip' in network:n
Error: Unnumbered network:n must not have attribute 'ip'
Error: Unnumbered network:n must not have attribute 'ip'
=END=

############################################################
=TITLE=NAT without IP
=PARAMS=--ipv6
=INPUT=
network:n1 = { nat:n = { } }
=END=
=ERROR=
Error: Missing IP address in nat:n of network:n1
Error: Missing IP address for network:n1
=END=

############################################################
=TITLE=Ignoring radius attribute at network
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; radius_attributes = { a = b; } }
=END=
=WARNING=
Warning: Ignoring 'radius_attributes' at network:n1
=END=

############################################################
=TITLE=Ignoring radius attribute at host
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120;
 host:h1 = { ip = ::a01:10a; radius_attributes = { a = b; } }
}
=END=
=WARNING=
Warning: Ignoring 'radius_attributes' at host:h1
=END=

############################################################
=TITLE=Bad identifier in radius attribute
=PARAMS=--ipv6
=INPUT=
network:n1 = {
 ip = ::a01:100/120; radius_attributes = { a.1 = 1; }
 host:id:a@b.c = { ip = ::a01:101; }
}
=END=
=ERROR=
Error: Invalid identifier 'a.1' in radius_attributes of network:n1
=END=

############################################################
=TITLE=Bad radius attribute with comment character
=PARAMS=--ipv6
=INPUT=
network:n1 = { radius_attributes = { banner = Welcome #two; } }
=END=
=ERROR=
Error: Expected ';' at line 1 of INPUT, at EOF
Aborted
=END=

############################################################
=TITLE=Bad value for restricting attribute
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; has_unenforceable = allow; }
=END=
=ERROR=
Error: Expected 'restrict', 'enable' or 'ok' in 'has_unenforceable' of network:n1
=END=

############################################################
=TITLE=Unexpected NAT attribute at network
=PARAMS=--ipv6
=INPUT=
network:n = {
 ip = ::a01:100/120;
 nat:n = { ip = ::a09:900/120; xyz; }
}
=END=
=ERROR=
Error: Unexpected attribute in nat:n of network:n: xyz
=END=

############################################################
=TITLE=Unexpected NAT attribute at host
=PARAMS=--ipv6
=INPUT=
network:n = {
 ip = ::a01:100/120;
 nat:n = { ip = ::a09:900/125; dynamic; }
 host:h = { ip = ::a01:10a; nat:n = { ip = ::a09:903; dynamic; } }
}
=END=
=ERROR=
Error: Unexpected attribute in nat:n of host:h: dynamic
=END=

############################################################
=TITLE=Unexpected NAT attribute at interface
=PARAMS=--ipv6
=INPUT=
network:n = {
 ip = ::a01:100/120;
 nat:n = { ip = ::a09:900/125; dynamic; }
}
router:r = {
 interface:n = { ip = ::a01:101; nat:n = { ip = ::a09:901; xyz; } }
}
=END=
=ERROR=
Error: Unexpected attribute in nat:n of interface:r.n: xyz
=END=

############################################################
=TITLE=Service without any rules
=PARAMS=--ipv6
=INPUT=
service:s1 = {
 user = ;
}
=END=
=ERROR=
Error: Must not define service:s1 without any rules
=END=

############################################################
=TITLE=Service without user
=PARAMS=--ipv6
=INPUT=
service:s1 = {
 permit src = user; dst = network:n1; prt = tcp 80;
}
=END=
=ERROR=
Error: Expected '=' at line 2 of INPUT, near "permit --HERE-->src"
Aborted
=END=

############################################################
=TITLE=Must not use 'user' outside of rule
=PARAMS=--ipv6
=INPUT=
group:g1 = user;
network:n1 = { ip = ::a01:100/120; }
service:s1 = {
 user = network:n1;
 permit src = user; dst = group:g1; prt = tcp 80;
}
=END=
=ERROR=
Error: Unexpected reference to 'user' in group:g1
=END=

############################################################
=TITLE=Duplicate network definition
=PARAMS=--ipv6
=INPUT=
-- file1
network:n1 = { ip = ::a01:100/120; }
-- file2
network:n1 = { ip = ::a01:200/120; }
router:r = {
 interface:n1;
}
=END=
=ERROR=
Error: Duplicate definition of network:n1 in file1 and file2
=END=

############################################################
=TITLE=Duplicate host definition
=PARAMS=--ipv6
=INPUT=
-- file1
network:n1 = { ip = ::a01:100/120; host:h1 = { ip = ::a01:10a; } }
-- file2
network:n2 = { ip = ::a01:200/120;
 host:h1 = { ip = ::a01:20a; }
 host:h1 = { ip = ::a01:20b; }
}
router:r = {
 interface:n1;
 interface:n2;
}
=END=
=ERROR=
Error: Duplicate definition of host:h1 in file1 and file2
Error: Duplicate definition of host:h1 in file2
=END=

############################################################
=TITLE=Reference non network in subnet_of
=PARAMS=--ipv6
=INPUT=
any:n1 = { link = network:n1; }
network:n1 = {
 ip = ::a01:100/120;
 subnet_of = any:n1;
}
=END=
=ERROR=
Error: Must only use network name in 'subnet_of' of network:n1
=END=

############################################################
=TITLE=Attribute subnet_of at non loopback interface
=PARAMS=--ipv6
=INPUT=
network:n = {
 ip = ::a01:100/120;
}
router:r = {
 interface:n = { ip = ::a01:101; subnet_of = network:n; }
}
=END=
=ERROR=
Error: Attribute 'subnet_of' must not be used at interface:r.n
 It is only valid together with attribute 'loopback'
=END=

############################################################
=TITLE=Unexpected token in aggregate
=PARAMS=--ipv6
=INPUT=
any:n = { xyz; x:yz; link = network:n1; }
network:n1 = { ip = ::a01:200/120; }
=END=
=ERROR=
Error: Unexpected attribute in any:n: xyz
Error: Unexpected attribute in any:n: x:yz
=END=

############################################################
=TITLE=Aggregate without attribute 'link'
=PARAMS=--ipv6
=INPUT=
any:n = { }
network:n1 = { ip = ::a01:200/120; }
=END=
=ERROR=
Error: Attribute 'link' must be defined for any:n
=END=

############################################################
=TITLE=Invalid attribute at aggregate with IP
=PARAMS=--ipv6
=INPUT=
owner:o = { admins = a@b.c; }
any:n = {
 link = network:n;ip = ::a00:0/112;
 owner = o; no_check_supernet_rules;
}
network:n = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Must not use attribute 'no_check_supernet_rules' if IP is set for any:n
=END=

############################################################
=TITLE=Valid attribute at aggregate with IP ::
=PARAMS=--ipv6
=INPUT=
owner:o = { admins = a@b.c; }
any:n = {
 link = network:n;
 ip = ::/0;
 owner = o;
 no_check_supernet_rules;
}
network:n = { ip = ::a01:100/120; }
=END=
=WARNING=NONE

############################################################
=TITLE=Untyped name in anchor
=PARAMS=--ipv6
=INPUT=
area:n = {
 anchor = n;
}
network:n = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Typed name expected in 'anchor' of area:n
Error: At least one of attributes 'border', 'inclusive_border' or 'anchor' must be defined for area:n
=END=

############################################################
=TITLE=Invalid attribute in router_attributes
=PARAMS=--ipv6
=INPUT=
area:n = {
 anchor = network:n;
 router_attributes = { xyz; }
}
network:n = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unexpected attribute in router_attributes of area:n: xyz
=END=

############################################################
=TITLE=Unexpected token in area
=PARAMS=--ipv6
=INPUT=
area:n = { xyz; anchor = network:n; x:yz; }
network:n = { ip = ::a01:100/120; }
=END=
=ERROR=
Error: Unexpected attribute in area:n: xyz
Error: Unexpected attribute in area:n: x:yz
=END=

############################################################
=TITLE=Unexpected token in crypto
=PARAMS=--ipv6
=INPUT=
crypto:c = { xyz; }
=END=
=ERROR=
Error: Unexpected attribute in crypto:c: xyz
Error: Missing 'type' for crypto:c
=END=

############################################################
=TITLE=Unexpected token in owner
=PARAMS=--ipv6
=INPUT=
owner:o = { xyz; }
network:n1 = { ip = ::a01:100/120; owner = o; }
=END=
=ERROR=
Error: Unexpected attribute in owner:o: xyz
Error: Missing attribute 'admins' in owner:o of network:n1
=END=

############################################################
# Shared topology
=TEMPL=topo
network:n1 = { ip = ::a01:100/120; }
network:n2 = { ip = ::a01:200/120; }
network:n3 = { ip = ::a01:300/120; }
router:r = {
 managed;
 model = ASA;
 interface:n1 = { ip = ::a01:101; hardware = n1; }
 interface:n2 = { ip = ::a01:201; hardware = n2; }
 interface:n3 = { ip = ::a01:301; hardware = n3; }
}
=END=

############################################################
=TITLE=Must reference user in rule
=PARAMS=--ipv6
=INPUT=
[[topo]]
service:s = {
 user = network:n1;
 permit src = network:n2; dst = network:n3; prt = ip;
}
=END=
=ERROR=
Error: Each rule of service:s must use keyword 'user'
=END=

############################################################
=TITLE=Equally reference user
=PARAMS=--ipv6
=INPUT=
[[topo]]
service:s = {
 user = network:n1;
 permit src = user, network:n2; dst = network:n3; prt = ip;
}
=END=
=ERROR=
Error: The sub-expressions of union in 'src' of service:s equally must
 either reference 'user' or must not reference 'user'
=END=

############################################################
=TITLE=Equally reference user with intersection
=PARAMS=--ipv6
=INPUT=
[[topo]]
service:s1 = {
 user = network:n1, network:n2;
 permit src = network:n3;
        dst = interface:r.n2,
              interface:[user].[all] &! interface:r.n2;
        prt = tcp 22;
}
=END=
=ERROR=
Error: The sub-expressions of union in 'dst' of service:s1 equally must
 either reference 'user' or must not reference 'user'
=END=

############################################################
=TITLE=Invalid attribute syntax in service
=PARAMS=--ipv6
=INPUT=
service:s1 = {
 overlaps = service:s2,,;
 user = host:h1;
 permit src = user; dst = network:n1; prt = tcp 80;
}
=END=
=ERROR=
Error: Unexpected separator ',' at line 2 of INPUT, near "service:s2,--HERE-->,;"
Aborted
=END=

############################################################
=TITLE=Invalid attribute at service
=PARAMS=--ipv6
=INPUT=
[[topo]]
service:s1 = {
 xyz;
 user = network:n1;
 permit src = user; dst = network:n2; prt = tcp 22;
}
=END=
=ERROR=
Error: Unexpected attribute in service:s1: xyz
=END=

############################################################
=TITLE=Invalid action in at service
=PARAMS=--ipv6
=INPUT=
service:s1 = {
 user = network:n1;
 allow src = user; dst = network:n2; prt = tcp 22;
}
=END=
=ERROR=
Error: Expected 'permit' or 'deny' at line 3 of INPUT, near " --HERE-->allow"
Aborted
=END=

############################################################
=TITLE=Invalid rule in at service
=PARAMS=--ipv6
=INPUT=
service:s1 = {
 user = network:n1;
 permit  dst = network:n2; src = user; prt = tcp 22;
}
=END=
=ERROR=
Error: Expected 'src' at line 3 of INPUT, near "permit  --HERE-->dst"
Aborted
=END=

############################################################
=TITLE=Invalid rule with 'foreach'
=PARAMS=--ipv6
=INPUT=
[[topo]]
service:s1 = {
 user = foreach network:n1, network:n2;
 permit src = user; dst = network:n3; prt = tcp 22;
}
=END=
=WARNING=
Warning: Each rule of service:s1 should reference 'user' in 'src' and 'dst'
 because service has keyword 'foreach'
=OUTPUT=
-- ipv6/r
! n1_in
access-list n1_in extended permit tcp ::a01:100/120 ::a01:300/120 eq 22
access-list n1_in extended deny ip any6 any6
access-group n1_in in interface n1
--
! n2_in
access-list n2_in extended permit tcp ::a01:200/120 ::a01:300/120 eq 22
access-list n2_in extended deny ip any6 any6
access-group n2_in in interface n2
--
! n3_in
access-list n3_in extended deny ip any6 any6
access-group n3_in in interface n3
=END=

############################################################
=TITLE=Empty list of elements after 'user', 'src', 'dst'
=PARAMS=--ipv6
=INPUT=
[[topo]]
service:s1 = {
 user = ;
 permit src = user; dst = network:n3; prt = tcp 22;
}
service:s2= {
 user = network:n1;
 permit src = ; dst = user; prt = tcp 80;
}
service:s3 = {
 user = network:n1;
 permit src = user; dst = ; prt = tcp 22;
}
=END=
=WARNING=
Warning: user of service:s1 is empty
Warning: src of rule in service:s2 is empty
Warning: dst of rule in service:s3 is empty
=END=

############################################################
=TITLE=Empty list in automatic group
=PARAMS=--ipv6
=INPUT=
[[topo]]
group:g1 = interface:[].[all];
service:s1 = {
 user = network:[], group:g1;
 permit src = user; dst = network:n1; prt = tcp 22;
}
=END=
=WARNING=
Warning: network:[..] of user of service:s1 is empty
Warning: interface:[..].[all] of group:g1 is empty
=END=

############################################################
=TITLE=Empty user and empty rules
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; }
group:g1 = ;
group:g2 = ;
protocolgroup:p1 = ;
service:s1 = {
 user = group:g1;
 permit src = user; dst = group:g2; prt = tcp 80;
}
service:s2 = {
 user = group:g1;
 permit src = user; dst = network:n1; prt = protocolgroup:p1;
}
service:s3 = {
 disabled;
 user = group:g1;
 permit src = user; dst = group:g2; prt = protocolgroup:p1;
}
=END=
=WARNING=
Warning: Must not define service:s1 with empty users and empty rules
Warning: Must not define service:s2 with empty users and empty rules
Warning: Must not define service:s3 with empty users and empty rules
=END=

############################################################
=TITLE=Non host as policy_distribution_point
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; }
router:r = {
 managed;
 model = ASA;
 policy_distribution_point = network:n1;
 interface:n1 = { ip = ::a01:101; hardware = n1; }
}
=END=
=ERROR=
Error: Expected type 'host:' in 'policy_distribution_point' of router:r
=END=

############################################################
=TITLE=Unknown host as policy_distribution_point
=PARAMS=--ipv6
=INPUT=
network:n1 = { ip = ::a01:100/120; }
router:r = {
 managed;
 model = ASA;
 policy_distribution_point = host:h1;
 interface:n1 = { ip = ::a01:101; hardware = n1; }
}
=END=
=WARNING=
Warning: Ignoring undefined host:h1 in 'policy_distribution_point' of router:r
=END=

############################################################
