############################################################
=TITLE=Warn on empty files
=INPUT=
--ipv6/empty
# Only comment
# network:n1 = { ip6 = ::a01:100/120; }
--ipv6/valid
# Generated by xyz; DO NOT EDIT.
# :-)
#
--ipv6/topo
network:n1 = { ip6 = ::a01:100/120; }
-- ipv6/dir/other

=WARNING=
Warning: Ignoring file 'ipv6/dir/other' without any content
Warning: Ignoring file 'ipv6/empty' without any content
=END=

############################################################
=TITLE=Disabled warning on empty file
=OPTIONS=--check_empty_files=0
=INPUT=
--ipv6/empty
# Only comment
--ipv6/topo
network:n1 = { ip6 = ::a01:100/120; }
=WARNING=NONE

############################################################
=TITLE=Token with non letter or digit UTF8 character
=INPUT=
# EQUAL TO OR GREATER-THAN
network:⋝3 = { ip6 = ::a01:100/120; }
=ERROR=
Error: Typed name expected at line 2 of INPUT, near "--HERE-->network:⋝3"
Aborted
=END=

############################################################
=TITLE=Invalid IP address
=INPUT=
network:n1 = { ip6 = ::a01:100o/24; }
=ERROR=
Error: Invalid CIDR address: ::a01:100o/24 in 'ip6' of network:n1
=END=

############################################################
=TITLE=Missing = after IP in anonymous aggregate
=INPUT=
network:n1 = { ip6 = ::a01:100/120; }
router:r = {
 managed;
 model = IOS;
 interface:n1 = { ip6 = ::a01:101; hardware = n1; }
}
service:s1 = {
 user = any:[ ip ::a01:0/112 & network:n1];
 permit src = user; dst = interface:r.n1; prt = tcp 22;
}
=ERROR=
Error: Expected '=' at line 8 of INPUT, near "ip --HERE-->::a01:0/112"
Aborted
=END=

############################################################
=TITLE=Invalid IP in anonymous aggregate
=INPUT=
network:n1 = { ip6 = ::a01:100/120; }
router:r = {
 managed;
 model = IOS;
 interface:n1 = { ip6 = ::a01:101; hardware = n1; }
}
service:s1 = {
 user = any:[ ip6 = ::a01:0 & network:n1];
 permit src = user; dst = interface:r.n1; prt = tcp 22;
}
=ERROR=
Error: Invalid CIDR address in any:[ip6 = ::a01:0 & ..] of user of service:s1
=END=

############################################################
=TITLE=IP and prefix don't match in anonymous aggregate
=INPUT=
network:n1 = { ip6 = ::a01:100/120; }
router:r = {
 managed;
 model = IOS;
 interface:n1 = { ip6 = ::a01:101; hardware = n1; }
}
service:s1 = {
 user = any:[ ip6 = ::a01:100/112 & network:n1];
 permit src = user; dst = interface:r.n1; prt = tcp 22;
}
=ERROR=
Error: IP and mask don't match in any:[ip6 = ::a01:100/112 & ..] of user of service:s1
=END=

############################################################
=TITLE=Unknown model for managed router
=INPUT=
router:R = {
 managed;
 model = foo;
 interface:N = { ip6 = ::a01:101; hardware = e0; }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Unknown model in router:R: foo
=END=

############################################################
=TITLE=Missing model for managed router
=INPUT=
router:R = {
 managed;
 interface:N = { ip6 = ::a01:101; hardware = e0; }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Missing 'model' for managed router:R
=END=

############################################################
=TITLE=Unknown extension for model ASA
=INPUT=
router:R = {
 managed;
 model = ASA, foo, bar;
 interface:N = { ip6 = ::a01:101; hardware = e0; }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Unknown extension in 'model' of router:R: foo
Error: Unknown extension in 'model' of router:R: bar
=END=

############################################################
=TITLE=Unknown extension for model IOS
=INPUT=
router:R = {
 managed;
 model = IOS, VPN;
 interface:N = { ip6 = ::a01:101; hardware = e0; }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Unknown extension in 'model' of router:R: VPN
=END=

############################################################
=TITLE=Unknown extension for model Linux
=INPUT=
router:R = {
 managed;
 model = Linux, xyz;
 interface:N = { ip6 = ::a01:101; hardware = e0; }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Unknown extension in 'model' of router:R: xyz
=END=

############################################################
=TITLE=Unexpected attribute no_check
=INPUT=
router:R = {
 managed;
 model = IOS;
 interface:N = { ip6 = ::a01:101; hardware = e0; no_check; }
}
network:N = { ip6 = ::a01:100/120; }
=WARNING=
Warning: Ignoring attribute 'no_check' at interface:R.N
=END=

############################################################
=TITLE=Unknown attribute in router
=INPUT=
router:R = {
 managed;
 model = ASA;
 xyz;
 interface:N = { ip6 = ::a01:101; hardware = e0; }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Unexpected attribute in router:R: xyz
=END=

############################################################
=TITLE=Unknown typed name in router
=INPUT=
router:R = {
 managed;
 model = ASA;
 interface:N = { ip6 = ::a01:101; hardware = e0; }
 x:y;
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Unexpected attribute in router:R: x:y
=END=

############################################################
=TITLE=Invalid hardware name with comment character
=INPUT=
router:R = {
 managed;
 model = ASA;
 interface:N = { ip6 = ::a01:101; hardware = e0#3; }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Expected ';' at line 5 of INPUT, near "--HERE-->}"
Aborted
=END=

############################################################
=TITLE=Missing hardware at interface
# Processing of attribute 'no_in_acl' internally uses value of
# hardware.
=INPUT=
router:R = {
 managed;
 model = ASA;
 interface:N = { ip6 = ::a01:101; no_in_acl; }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Missing 'hardware' for interface:R.N
=END=

############################################################
=TITLE=Model doesn't support no_in_acl
=INPUT=
router:R = {
 managed;
 model = Linux;
 interface:N = { ip6 = ::a01:101; no_in_acl; hardware = N; }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: router:R doesn't support outgoing ACL
=END=

############################################################
=TITLE=Multiple interfaces with attribute 'no_in_acl'
=INPUT=
network:N1 = { ip6 = ::a01:100/120; }
network:N2 = { ip6 = ::a01:200/120; }
router:R = {
 managed;
 model = ASA;
 interface:N1 = { ip6 = ::a01:101; no_in_acl; hardware = n1; }
 interface:N2 = { ip6 = ::a01:201; no_in_acl; hardware = n2; }
}
=ERROR=
Error: At most one interface of router:R may use flag 'no_in_acl'
=END=

############################################################
=TITLE=Multiple interfaces with 'no_in_acl' at one hardware
=INPUT=
network:N1 = { ip6 = ::a01:100/120; }
network:N2 = { ip6 = ::a01:200/120; }
router:R = {
 managed;
 model = ASA;
 interface:N1 = { ip6 = ::a01:101; no_in_acl; hardware = x; }
 interface:N2 = { ip6 = ::a01:201; no_in_acl; hardware = x; }
}
=ERROR=
Error: Only one logical interface allowed at hardware 'x' of router:R
 because of attribute 'no_in_acl'
=END=

############################################################
=TITLE=Unexpected attribute at interface
=INPUT=
router:R = {
 interface:N = { ip6 = ::a01:101; foo }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Expected '=' at line 2 of INPUT, near "foo --HERE-->}"
Aborted
=END=

############################################################
=TITLE=Unknown attribute at interface of dual stack router
=TODO= No IPv6
# Duplicate error message can't be avoided.
=INPUT=
router:R = {
 interface:N = { ip6 = ::a01:101; ip6 = 2001:db8:1:1::1; foo; }
}
network:N = { ip6 = ::a01:100/120; ip6 = 2001:db8:1:1::/64; }
=ERROR=
Error: Unexpected attribute in interface:R.N: foo
Error: Unexpected attribute in interface:R.N: foo
=END=

############################################################
=TITLE=Bad typed name as attribute of interface
=INPUT=
router:R = {
 interface:N = { ip6 = ::a01:101; primary:p = {} }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Unexpected attribute in interface:R.N: primary:p
=END=

############################################################
=TITLE=Short interface at managed router
=INPUT=
router:R = {
 managed;
 model = ASA;
 interface:N = { hardware = inside; }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Short definition of interface:R.N not allowed
=END=

############################################################
=TITLE=Empty list of IP addresses
=TODO= No IPv6
=INPUT=
router:R = {
 interface:N = { ip6 = ; ip6 = ; }
}
network:N = { ip6 = ::a01:100/120; ip6 = 2001:db8:1:1::/64; }
=ERROR=
Error: List of values expected in 'ip6' of interface:R.N
Error: List of values expected in 'ip6' of interface:R.N
=END=

############################################################
=TITLE=Negotiated interface with additional IP address
=INPUT=
router:R = {
 interface:N = { negotiated6; ip6 = ::a01:101; }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Must not use both, "ip6" and "negotiated6" in interface:R.N
=END=

############################################################
=TITLE=Secondary interface without IP
=INPUT=
router:R = {
 interface:N = { ip6 = ::a01:101; secondary:second = {} }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Missing 'ip6' in "secondary:second" of interface:R.N
=END=

############################################################
=TITLE=Secondary interface with bad attribute
=INPUT=
router:R = {
 interface:N = { ip6 = ::a01:101; secondary:second = { foo; } }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Missing 'ip6' in "secondary:second" of interface:R.N
Error: Unexpected attribute in secondary:second of interface:R.N: foo
=END=

############################################################
=TITLE=Unnumbered with secondary interface
=INPUT=
router:R = {
 interface:N = { unnumbered6; secondary:second = { ip6 = ::a01:101; } }
}
network:N = { unnumbered6; }
=ERROR=
Error: interface:R.N without IP address must not have secondary address
=END=

############################################################
=TITLE=Negotiated with secondary interface
=INPUT=
router:R = {
 interface:N = { negotiated6; secondary:second = { ip6 = ::a01:101; } }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: interface:R.N without IP address must not have secondary address
=END=

############################################################
=TITLE=Single secondary interface
=INPUT=
router:R = {
 interface:N = { secondary:second = { ip6 = ::a01:101; } }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: interface:R.N without IP address must not have secondary address
=END=

############################################################
=TITLE=Virtual interface with bad attribute
=INPUT=
router:R = {
 interface:N = { ip6 = ::a01:101; virtual = { foo; } }
}
network:N = { ip6 = ::a01:100/120; }
=ERROR=
Error: Missing 'ip6' in "virtual" of interface:R.N
Error: Unexpected attribute in 'virtual' of interface:R.N: foo
=END=

############################################################
=TITLE=Typed name expected
=TODO= No IPv6
=INPUT=
network = {
=ERROR=
Error: Typed name expected at line 1 of INPUT, near "--HERE-->network"
Aborted
=END=

############################################################
=TITLE=Unknown global definition
=TODO= No IPv6
=INPUT=
networkX:n1 = {
=ERROR=
Error: Unknown global definition at line 1 of INPUT, near "--HERE-->networkX:n1"
Aborted
=END=

############################################################
=TITLE=Missing '}' after network definition
=INPUT=
network:n1 = {
 ip6 = ::a01:100/120;
 host:h1 = { ::a01:10a; }
 FOO = BAR;
network:n2 = { ip6 = ::a01:200/120; }
network:n3 = { ip6 = ::a01:300/120; }
=ERROR=
Error: Expected '}' at line 5 of INPUT, near "--HERE-->network:n2"
Aborted
=END=

############################################################
=TITLE=Missing '}' after owner definition
=TODO= No IPv6
=INPUT=
owner:o1 = {
 admins = a1@b.c;
owner:o2 = { admins = a2@b.c; }
=ERROR=
Error: Expected '}' at line 3 of INPUT, near "--HERE-->owner:o2"
Aborted
=END=

############################################################
=TITLE=Unexpected definition after missing ';' in list
=TODO= No IPv6
=INPUT=
group:g1 =
 host:h1,
 host:h2,
network:n2 = { ip6 = ::a01:200/120; }
network:n3 = { ip6 = ::a01:300/120; }
=ERROR=
Error: Expected ';' at line 4 of INPUT, near "network:n2 --HERE-->= { ip"
Aborted
=END=

############################################################
=TITLE=Invalid character in network name
=TODO= No IPv6
=INPUT=
network:n1@vrf123 = {}
=ERROR=
Error: Invalid identifier in definition of 'network:n1@vrf123'
Error: Missing IP address for network:n1@vrf123
=END=

############################################################
=TITLE=Invalid character in router name
=INPUT=
router:r1/bridged-part = {}
=ERROR=
Error: Invalid identifier in definition of 'router:r1/bridged-part'
=END=

############################################################
=TITLE=Invalid character in area name
=TODO= No IPv6
=INPUT=
area:a1@vrf123 = {}
=ERROR=
Error: Invalid identifier in definition of 'area:a1@vrf123'
Error: At least one of attributes 'border', 'inclusive_border' or 'anchor' must be defined for area:a1@vrf123
=END=

############################################################
=TITLE=Unexpected end of file
=TODO= No IPv6
=INPUT=
network:n1
=ERROR=
Error: Expected '=' at line 1 of INPUT, at EOF
Aborted
=END=

############################################################
=TITLE=Identifier expected  at EOF
=TODO= No IPv6
=INPUT=
network:n1 = { owner =
=ERROR=
Error: Expected something at line 1 of INPUT, at EOF
Aborted
=END=

############################################################
=TITLE=Identifier expected
=INPUT=
network:n1 = { owner = }
=ERROR=
Error: Unexpected separator '}' at line 1 of INPUT, near "owner = --HERE-->}"
Aborted
=END=

############################################################
=TITLE=Invalid identifier in reference
=INPUT=
network:n1 = { ip6 = ::a01:100/120; owner = a/b; }
=WARNING=
Warning: Ignoring undefined owner:a/b of network:n1
=END=

############################################################
=TITLE=Invalid identifier in partition
=INPUT=
network:n1 = { ip6 = ::a01:100/120; partition = a/b; }
=ERROR=
Error: Invalid identifier in 'partition' of network:n1: a/b
=END=

############################################################
=TITLE=String expected
=TODO= No IPv6
=INPUT=
owner:o1 = { admins = ; }
=ERROR=
Error: List of values expected in 'admins' of owner:o1
=END=

############################################################
=TITLE=Single value expected
=INPUT=
network:n1 = { ip6 = ::a01:100/120, ::a01:200/120; }
=ERROR=
Error: Single value expected in 'ip6' of network:n1
Error: Invalid CIDR address:  in 'ip6' of network:n1
=END=

############################################################
=TITLE=Structured value expected
=TODO= No IPv6
=INPUT=
network:n1 = { ip6 = ::a01:100/120; host:h1 = ::a01:10a; host:h2; }
=ERROR=
Error: Structured value expected in 'host:h1'
Error: Missing IP address for host:h1
Error: Structured value expected in 'host:h2'
Error: Missing IP address for host:h2
=END=

############################################################
=TITLE=No value expected
=INPUT=
network:n1 = { ip6 = ::a01:100/120; has_subnets = yes; }
=ERROR=
Error: No value expected for flag 'has_subnets' of network:n1
=END=

############################################################
=TITLE=Comma expected in union of values (1)
=TODO= No IPv6
=INPUT=
group:g1 = host:h1 host:h2;
=ERROR=
Error: Expected ';' at line 1 of INPUT, near "host:h1 --HERE-->host:h2"
Aborted
=END=

############################################################
=TITLE=Comma expected in list of values (2)
=TODO= No IPv6
=INPUT=
owner:o = { admins = a@b.c x@y.z; }
=ERROR=
Error: Expected ';' at line 1 of INPUT, near "a@b.c --HERE-->x@y.z"
Aborted
=END=

############################################################
=TITLE=Typed name expected
=INPUT=
group:g1 = host:;
=ERROR=
Error: Typed name expected at line 1 of INPUT, near "group:g1 = --HERE-->host:"
Aborted
=END=

############################################################
=TITLE=Missing type
=TODO= No IPv6
=INPUT=
group:g1 = :n1;
=ERROR=
Error: Typed name expected at line 1 of INPUT, near "group:g1 = --HERE-->:n1"
Aborted
=END=

############################################################
=TITLE=Bad hostname in definition
=INPUT=
network:n1 = {
 ip6 = ::a01:100/120;
 host:id: = { ip6 = ::a01:10a; }
 host:@h11 = { ip6 = ::a01:10b; }
}
=ERROR=
Error: Invalid name in definition of 'host:id:'
Error: Invalid identifier in definition of 'host:@h11'
=END=

############################################################
=TITLE=Bad hostname in reference
=INPUT=
service:s1 = {
 user = network:n1, host:id:;
 permit src = user; dst = user; prt = ip;
}
network:n1 = { ip6 = ::a01:100/120; }
=ERROR=
Error: Can't resolve host:id: in user of service:s1
=END=

############################################################
=TITLE=Bad network name in definition
=INPUT=
network:n1@vrf = { ip6 = ::a01:100/120; }
=ERROR=
Error: Invalid identifier in definition of 'network:n1@vrf'
=END=

############################################################
=TITLE=Bad network name in reference
=INPUT=
service:s1 = {
 user = network:n1, network:n1@vrf:;
 permit src = user; dst = user; prt = ip;
}
network:n1 = { ip6 = ::a01:100/120; }
=ERROR=
Error: Can't resolve network:n1@vrf: in user of service:s1
=END=

############################################################
=TITLE=Empty interface name
=TODO= No IPv6
=INPUT=
group:g1 = interface:;
=ERROR=
Error: Typed name expected at line 1 of INPUT, near "group:g1 = --HERE-->interface:"
Aborted
=END=

############################################################
=TITLE=Interface name without dot
=TODO= No IPv6
=INPUT=
group:g1 = interface:r;
=ERROR=
Error: Interface name expected at line 1 of INPUT, near "group:g1 = --HERE-->interface:r"
Aborted
=END=

############################################################
=TITLE=Interface name with empty router part
=TODO= No IPv6
=INPUT=
group:g1 = interface:.n;
=ERROR=
Error: Interface name expected at line 1 of INPUT, near "group:g1 = --HERE-->interface:.n"
Aborted
=END=

############################################################
=TITLE=Interface name with empty network part
=TODO= No IPv6
=INPUT=
group:g1 = interface:r.;
=ERROR=
Error: Interface name expected at line 1 of INPUT, near "group:g1 = --HERE-->interface:r."
Aborted
=END=

############################################################
=TITLE=Invalid interface names
=INPUT=
service:s1 = {
 user = network:n1, interface:r1.n1@vrf2, interface:r.n.123.nn;
 permit src = user; dst = user; prt = ip;
}
network:n1 = { ip6 = ::a01:100/120; }
=ERROR=
Error: Can't resolve interface:r1.n1@vrf2 in user of service:s1
Error: Can't resolve interface:r.n.123.nn in user of service:s1
=END=

############################################################
=TITLE=Invalid name of loopback interface
=INPUT=
router:r1 = {
 interface:lo-::a01:203 = { ip6 = ::a01:203; loopback; }
}
=ERROR=
Error: Invalid identifier in 'interface:lo-::a01:203' of 'router:r1'
=END=

############################################################
=TITLE=Missing [any|all]
=TODO= No IPv6
=INPUT=
group:g1 = interface:r1.[ ;
=ERROR=
Error: Expected [auto|all] at line 1 of INPUT, near "interface:r1.[ --HERE-->;"
Aborted
=END=

############################################################
=TITLE=Bad auto interface
=TODO= No IPv6
=INPUT=
group:g1 = interface:r.[foo];
=ERROR=
Error: Expected [auto|all] at line 1 of INPUT, near "interface:r.[--HERE-->foo]"
Aborted
=END=

############################################################
=TITLE=Unexpected network name in interfaces of network
=TODO= No IPv6
=INPUT=
group:g1 = interface:[network:n1].n2;
=ERROR=
Error: Expected '.[' at line 1 of INPUT, near "interface:[network:n1]--HERE-->.n2"
Aborted
=END=

############################################################
=TITLE=Bad group name in definition
=TODO= No IPv6
=INPUT=
group:a@b = ;
=ERROR=
Error: Invalid identifier in definition of 'group:a@b'
=END=

############################################################
=TITLE=Bad NAT name
=TODO= No IPv6
=INPUT=
network:n = { nat:a+b = { ip6 = ::a09:900/120; } ip6 = ::a01:100/120; }
=ERROR=
Error: Expected '=' at line 1 of INPUT, near "nat:a--HERE-->+b"
Aborted
=END=

############################################################
=TITLE=Bad crypto in hub
=INPUT=
network:n = { ip6 = ::a01:100/120; }
router:r = {
 managed;
 model = IOS;
 interface:n = { ip6 = ::a01:101; hardware = n; hub = foo, tool:bar; }
}
=ERROR=
Error: Expected type 'crypto:' in 'hub' of interface:r.n
Error: Expected type 'crypto:' in 'hub' of interface:r.n
=END=

############################################################
=TITLE=Bad crypto in spoke
=INPUT=
network:n = { ip6 = ::a01:100/120; }
router:r = {
 managed;
 model = IOS;
 interface:n = { ip6 = ::a01:101; hardware = n; spoke = cyrpto:n; }
}
=ERROR=
Error: Expected type 'crypto:' in 'spoke' of interface:r.n
=END=

############################################################
=TITLE=Ignore cert_id
=INPUT=
network:n = { ip6 = ::a01:100/120; cert_id = a.b.c; }
=WARNING=
Warning: Ignoring 'cert_id' at network:n
=END=

############################################################
=TITLE=Missing cert_id
=INPUT=
network:n = {
 ip6 = ::a01:100/120;
 host:h = { range6 = ::a01:108 - ::a01:10f; ldap_id = a@b.c; }
}
=ERROR=
Error: Missing attribute 'cert_id' at network:n having hosts with attribute 'ldap_id'
=END=

############################################################
=TITLE=Bad cert_id
=INPUT=
network:n = {
 ip6 = ::a01:100/120; cert_id = @b.c;
 host:h = { ip6 = ::a01:101; ldap_id = a@b.c; }
}
=ERROR=
Error: Attribute 'ldap_Id' must only be used together with IP range at host:h
Error: Domain name expected in attribute 'cert_id' of network:n
=END=

############################################################
=TITLE=Bad managed attribute
=TODO= No IPv6
=INPUT=
router:r = {
 managed xxx;
 interface:n;
}
=ERROR=
Error: Expected '=' at line 2 of INPUT, near "managed --HERE-->xxx"
Aborted
=END=

############################################################
=TITLE=Unexpected managed type
=INPUT=
router:r = {
 managed = xxx;
 interface:n;
}
network:n = { ip6 = ::a01:100/120; }
=ERROR=
Error: Invalid value for 'managed' of router:r: xxx
=END=

############################################################
=TITLE=Empty value at managed attribute
=INPUT=
router:r = {
 managed = ;
 interface:n;
}
network:n = { ip6 = ::a01:100/120; }
=ERROR=
Error: Single value expected in 'managed' of router:r
=END=

############################################################
=TITLE=Unknown routing protocol
=INPUT=
router:r = {
 routing = xyz;
 interface:n = { routing = abc; }
}
network:n = { ip6 = ::a01:100/120; }
=ERROR=
Error: Unknown routing protocol in 'routing' of router:r
Error: Unknown routing protocol in 'routing' of interface:r.n
=END=

############################################################
=TITLE=Must not use 'routing = manual' at interface
=INPUT=
network:n1 = { ip6 = ::a01:100/120; }
router:r1 = {
 managed;
 model = ASA;
 interface:n1 = { ip6 = ::a01:101; hardware = n1; routing = manual; }
}
=WARNING=
Warning: 'routing=manual' must only be applied to router, not to interface:r1.n1
=END=

############################################################
=TITLE=Bad typed name as attribute of host
=INPUT=
network:n = {
 ip6 = ::a01:100/120;
 host:h = { ip6 = ::a01:101; xy:z; }
}
=ERROR=
Error: Unexpected attribute in host:h: xy:z
=END=

############################################################
=TITLE=Bad token as attribute of host
=INPUT=
network:n = {
 host:h = { ip6 = ::a01:101; ; }
}
=ERROR=
Error: Unexpected separator ';' at line 2 of INPUT, near "::a01:101; --HERE-->; }"
Aborted
=END=

############################################################
=TITLE=Bad typed name as attribute of network
=TODO= No IPv6
=INPUT=
network:n = { xy:z; }
=ERROR=
Error: Unexpected attribute in network:n: xy:z
Error: Missing IP address for network:n
=END=

############################################################
=TITLE=Bad token as attribute of network
=TODO= No IPv6
=INPUT=
network:n = { ; }
=ERROR=
Error: Unexpected separator ';' at line 1 of INPUT, near "network:n = { --HERE-->; }"
Aborted
=END=

############################################################
=TITLE=Network and host without IP
=TODO= No IPv6
=INPUT=
network:n = { host:h1 = {} }
=ERROR=
Error: Missing IP address for host:h1
Error: Missing IP address for network:n
=END=

############################################################
=TITLE=Duplicate IP in network
=INPUT=
network:n = { ip6 = ::a01:100/120; unnumbered6; ip6 = ::a01:200/120; }
=ERROR=
Error: Duplicate attribute 'ip6' in network:n
Error: Must not use both, "unnumbered6" and "ip6" in network:n
=END=

############################################################
=TITLE=NAT without IP
=TODO= No IPv6
=INPUT=
network:n1 = { nat:n = { } }
=ERROR=
Error: Missing IP address in nat:n of network:n1
Error: Missing IP address for network:n1
=END=

############################################################
=TITLE=Ignoring vpn attribute at network
=INPUT=
network:n1 = { ip6 = ::a01:100/120; vpn_attributes = { a = b; } }
=WARNING=
Warning: Ignoring 'vpn_attributes' at network:n1
=END=

############################################################
=TITLE=Ignoring vpn attribute at host
=INPUT=
network:n1 = { ip6 = ::a01:100/120;
 host:h1 = { ip6 = ::a01:10a; vpn_attributes = { a = b; } }
}
=WARNING=
Warning: Ignoring 'vpn_attributes' at host:h1
=END=

############################################################
=TITLE=Bad identifier in vpn attribute
=INPUT=
network:n1 = {
 ip6 = ::a01:100/120; vpn_attributes = { a.1 = 1; }
 host:id:a@b.c = { ip6 = ::a01:101; }
}
=ERROR=
Error: Invalid identifier 'a.1' in vpn_attributes of network:n1
=END=

############################################################
=TITLE=Bad vpn attribute with comment character
=TODO= No IPv6
=INPUT=
network:n1 = { vpn_attributes = { banner = Welcome #two; } }
=ERROR=
Error: Expected ';' at line 1 of INPUT, at EOF
Aborted
=END=

############################################################
=TITLE=Bad value for restricting attribute
=INPUT=
network:n1 = { ip6 = ::a01:100/120; has_unenforceable = allow; }
=ERROR=
Error: Expected 'restrict', 'enable' or 'ok' in 'has_unenforceable' of network:n1
=END=

############################################################
=TITLE=Unexpected NAT attribute at network
=TODO= No IPv6
=INPUT=
network:n = {
 ip6 = ::a01:100/120;
 nat:n = { ip6 = ::a09:900/120; xyz; }
}
=ERROR=
Error: Unexpected attribute in nat:n of network:n: xyz
=END=

############################################################
=TITLE=Unexpected NAT attribute at host
=TODO= No IPv6
=INPUT=
network:n = {
 ip6 = ::a01:100/120;
 nat:n = { ip6 = ::a09:900/125; dynamic; }
 host:h = { ip6 = ::a01:10a; nat:n = { ip6 = ::a09:903; dynamic; } }
}
=ERROR=
Error: Expecting exactly one attribute 'ip6' in nat:n of host:h
=END=

############################################################
=TITLE=Unexpected NAT attribute at interface
=TODO= No IPv6
=INPUT=
network:n = {
 ip6 = ::a01:100/120;
 nat:n = { ip6 = ::a09:900/125; dynamic; }
}
router:r = {
 interface:n = { ip6 = ::a01:101; nat:n = { ip6 = ::a09:901; xyz; } }
}
=ERROR=
Error: Unexpected attribute in nat:n of interface:r.n: xyz
=END=

############################################################
=TITLE=Service without any rules
=TODO= No IPv6
=INPUT=
service:s1 = {
 user = ;
}
=ERROR=
Error: Must not define service:s1 without any rules
=END=

############################################################
=TITLE=user-user rule together with normal rule
=TODO= No IPv6
=INPUT=
service:s1 = {
 user = network:n1, network:n2;
 permit src = user; dst = user; prt = ip;
 permit src = user; dst = network:n3; prt = tcp 80;
}
=ERROR=
Error: Must not define service:s1 having both user-user rule and normal rule
=END=

############################################################
=TITLE=Service without user
=TODO= No IPv6
=INPUT=
service:s1 = {
 permit src = user; dst = network:n1; prt = tcp 80;
}
=ERROR=
Error: Expected '=' at line 2 of INPUT, near "permit --HERE-->src"
Aborted
=END=

############################################################
=TITLE=Must not use 'user' outside of rule
=INPUT=
group:g1 = user;
network:n1 = { ip6 = ::a01:100/120; }
service:s1 = {
 user = network:n1;
 permit src = user; dst = group:g1; prt = tcp 80;
}
=ERROR=
Error: Unexpected reference to 'user' in group:g1
=END=

############################################################
=TITLE=Duplicate network definition
=INPUT=
-- file1
network:n1 = { ip6 = ::a01:100/120; }
-- file2
network:n1 = { ip6 = ::a01:200/120; }
router:r = {
 interface:n1;
}
=ERROR=
Error: Duplicate definition of network:n1 in file1 and file2
=END=

############################################################
=TITLE=Duplicate host definition
=INPUT=
-- file1
network:n1 = { ip6 = ::a01:100/120; host:h1 = { ip6 = ::a01:10a; } }
-- file2
network:n2 = { ip6 = ::a01:200/120;
 host:h1 = { ip6 = ::a01:20a; }
 host:h1 = { ip6 = ::a01:20b; }
}
router:r = {
 interface:n1;
 interface:n2;
}
=ERROR=
Error: Duplicate definition of host:h1 in file1 and file2
Error: Duplicate definition of host:h1 in file2
=END=

############################################################
=TITLE=Reference non network in subnet_of
=INPUT=
any:n1 = { link = network:n1; }
network:n1 = {
 ip6 = ::a01:100/120;
 subnet_of = any:n1;
}
=ERROR=
Error: Must only use network name in 'subnet_of' of network:n1
=END=

############################################################
=TITLE=Attribute subnet_of at non loopback interface
=INPUT=
network:n = {
 ip6 = ::a01:100/120;
}
router:r = {
 interface:n = { ip6 = ::a01:101; subnet_of = network:n; }
}
=ERROR=
Error: Attribute 'subnet_of' must not be used at interface:r.n
 It is only valid together with attribute 'loopback'
=END=

############################################################
=TITLE=Unexpected token in aggregate
=INPUT=
any:n = { xyz; x:yz; link = network:n1; }
network:n1 = { ip6 = ::a01:200/120; }
=ERROR=
Error: Unexpected attribute in any:n: xyz
Error: Unexpected attribute in any:n: x:yz
=END=

############################################################
=TITLE=Aggregate without attribute 'link'
=TODO= No IPv6
=INPUT=
any:n = { nat:h = { hidden; } }
=ERROR=
Error: Attribute 'link' must be defined for any:n
=END=

############################################################
=TITLE=Invalid attribute at aggregate with IP
=INPUT=
owner:o = { admins = a@b.c; }
any:n = {
 link = network:n;ip6 = ::a00:0/112;
 owner = o; no_check_supernet_rules;
}
network:n = { ip6 = ::a01:100/120; }
=ERROR=
Error: Must not use attribute 'no_check_supernet_rules' if IP is set for any:n
=END=

############################################################
=TITLE=Valid attribute at aggregate with IP ::
=INPUT=
owner:o = { admins = a@b.c; }
any:n = {
 link = network:n;
 owner = o;
 no_check_supernet_rules;
}
network:n = { ip6 = ::a01:100/120; }
=WARNING=NONE

############################################################
=TITLE=Untyped name in anchor
=TODO= No IPv6
=INPUT=
area:n = {
 anchor = n;
}
=ERROR=
Error: Typed name expected in 'anchor' of area:n
Error: At least one of attributes 'border', 'inclusive_border' or 'anchor' must be defined for area:n
=END=

############################################################
=TITLE=Invalid attribute in router_attributes
=INPUT=
area:n = {
 anchor = network:n;
 router_attributes = { xyz; }
}
network:n = { ip6 = ::a01:100/120; }
=ERROR=
Error: Unexpected attribute in router_attributes of area:n: xyz
=END=

############################################################
=TITLE=Unexpected token in area
=INPUT=
area:n = { xyz; anchor = network:n; x:yz; }
network:n = { ip6 = ::a01:100/120; }
=ERROR=
Error: Unexpected attribute in area:n: xyz
Error: Unexpected attribute in area:n: x:yz
=END=

############################################################
=TITLE=Unexpected token in crypto
=TODO= No IPv6
=INPUT=
crypto:c = { xyz; }
=ERROR=
Error: Unexpected attribute in crypto:c: xyz
Error: Missing 'type' for crypto:c
=END=

############################################################
=TITLE=Unexpected token in owner
=INPUT=
owner:o = { xyz; }
network:n1 = { ip6 = ::a01:100/120; owner = o; }
=ERROR=
Error: Unexpected attribute in owner:o: xyz
Error: Missing attribute 'admins' in owner:o of network:n1
=END=

############################################################
# Shared topology
=TEMPL=topo
network:n1 = { ip6 = ::a01:100/120; }
network:n2 = { ip6 = ::a01:200/120; }
network:n3 = { ip6 = ::a01:300/120; }
router:r = {
 managed;
 model = ASA;
 interface:n1 = { ip6 = ::a01:101; hardware = n1; }
 interface:n2 = { ip6 = ::a01:201; hardware = n2; }
 interface:n3 = { ip6 = ::a01:301; hardware = n3; }
}
=END=

############################################################
=TITLE=Must reference user in rule
=INPUT=
[[topo]]
service:s = {
 user = network:n1;
 permit src = network:n2; dst = network:n3; prt = ip;
}
=ERROR=
Error: Each rule of service:s must use keyword 'user'
=END=

############################################################
=TITLE=Equally reference user
=INPUT=
[[topo]]
service:s = {
 user = network:n1;
 permit src = user, network:n2; dst = network:n3; prt = ip;
}
=ERROR=
Error: The sub-expressions of union in 'src' of service:s equally must
 either reference 'user' or must not reference 'user'
=END=

############################################################
=TITLE=Equally reference user with intersection
=INPUT=
[[topo]]
service:s1 = {
 user = network:n1, network:n2;
 permit src = network:n3;
        dst = interface:r.n2,
              interface:[user].[all] &! interface:r.n2;
        prt = tcp 22;
}
=ERROR=
Error: The sub-expressions of union in 'dst' of service:s1 equally must
 either reference 'user' or must not reference 'user'
=END=

############################################################
=TITLE=Invalid attribute syntax in service
=TODO= No IPv6
=INPUT=
service:s1 = {
 overlaps = service:s2,,;
 user = host:h1;
 permit src = user; dst = network:n1; prt = tcp 80;
}
=ERROR=
Error: Unexpected separator ',' at line 2 of INPUT, near "service:s2,--HERE-->,;"
Aborted
=END=

############################################################
=TITLE=Invalid attribute at service
=TODO= No IPv6
=INPUT=
service:s1 = {
 xyz;
 user = network:n1;
 permit src = user; dst = network:n2; prt = tcp 22;
}
=ERROR=
Error: Unexpected attribute in service:s1: xyz
=END=

############################################################
=TITLE=Invalid action in at service
=TODO= No IPv6
=INPUT=
service:s1 = {
 user = network:n1;
 allow src = user; dst = network:n2; prt = tcp 22;
}
=ERROR=
Error: Expected 'permit' or 'deny' at line 3 of INPUT, near " --HERE-->allow"
Aborted
=END=

############################################################
=TITLE=Invalid rule in at service
=TODO= No IPv6
=INPUT=
service:s1 = {
 user = network:n1;
 permit  dst = network:n2; src = user; prt = tcp 22;
}
=ERROR=
Error: Expected 'src' at line 3 of INPUT, near "permit  --HERE-->dst"
Aborted
=END=

############################################################
=TITLE=Invalid rule with 'foreach'
=INPUT=
[[topo]]
service:s1 = {
 user = foreach network:n1, network:n2;
 permit src = user; dst = network:n3; prt = tcp 22;
}
=WARNING=
Warning: Each rule of service:s1 should reference 'user' in 'src' and 'dst'
 because service has keyword 'foreach'
=OUTPUT=
-- ipv6/r
! n1_in
access-list n1_in extended permit tcp ::a01:100/120 ::a01:300/120 eq 22
access-list n1_in extended deny ip any6 any6
access-group n1_in in interface n1
--
! n2_in
access-list n2_in extended permit tcp ::a01:200/120 ::a01:300/120 eq 22
access-list n2_in extended deny ip any6 any6
access-group n2_in in interface n2
--
! n3_in
access-list n3_in extended deny ip any6 any6
access-group n3_in in interface n3
=END=

############################################################
=TITLE=Empty list of elements after 'user', 'src', 'dst'
=INPUT=
[[topo]]
service:s1 = {
 user = ;
 permit src = user; dst = network:n3; prt = tcp 22;
}
service:s2= {
 user = network:n1;
 permit src = ; dst = user; prt = tcp 80;
}
service:s3 = {
 user = network:n1;
 permit src = user; dst = ; prt = tcp 22;
}
=WARNING=
Warning: user of service:s1 is empty
Warning: src of rule in service:s2 is empty
Warning: dst of rule in service:s3 is empty
=END=


############################################################
=TITLE=Ignore empty list of elements after 'user'
=INPUT=
[[topo]]
service:s1 = {
 user = ;
 permit src = user; dst = network:n3; prt = tcp 22;
}
=WARNING=NONE
=OPTIONS=--check_service_empty_user=0

############################################################
=TITLE=Empty list of elements after 'prt'
=INPUT=
[[topo]]
service:s1 = {
 user = network:n1;
 permit src = user; dst = network:n2; prt = ;
}
=ERROR=
Error: List of values expected in 'prt' of service:s1
=END=

############################################################
=TITLE=Empty list in automatic group
=INPUT=
[[topo]]
group:g1 = interface:[].[all];
service:s1 = {
 user = network:[], group:g1;
 permit src = user; dst = network:n1; prt = tcp 22;
}
=WARNING=
Warning: network:[..] of user of service:s1 is empty
Warning: interface:[..].[all] of group:g1 is empty
=END=

############################################################
=TITLE=Empty list in automatic group with attribute
=INPUT=
[[topo]]
service:s1 = {
 user = interface:[managed & ].[all];
 permit src = user; dst = network:n1, any:[ip6 = ::a01:0/112 & ]; prt = tcp 22;
}
=WARNING=
Warning: interface:[..].[all] of user of service:s1 is empty
Warning: any:[..] of dst of rule in service:s1 is empty
=END=

############################################################
=TITLE=Empty user and empty rules
=INPUT=
network:n1 = { ip6 = ::a01:100/120; }
group:g1 = ;
group:g2 = ;
protocolgroup:p1 = ;
service:s1 = {
 user = group:g1;
 permit src = user; dst = group:g2; prt = tcp 80;
}
service:s2 = {
 user = group:g1;
 permit src = user; dst = network:n1; prt = protocolgroup:p1;
}
service:s3 = {
 disabled;
 user = group:g1;
 permit src = user; dst = group:g2; prt = protocolgroup:p1;
}
=WARNING=
Warning: Must not define service:s1 with empty users and empty rules
Warning: Must not define service:s2 with empty users and empty rules
Warning: Must not define service:s3 with empty users and empty rules
=END=

############################################################
=TITLE=Non host as policy_distribution_point
=INPUT=
network:n1 = { ip6 = ::a01:100/120; }
router:r = {
 managed;
 model = ASA;
 policy_distribution_point = network:n1;
 interface:n1 = { ip6 = ::a01:101; hardware = n1; }
}
=ERROR=
Error: Expected type 'host:' in 'policy_distribution_point' of router:r
=END=

############################################################
=TITLE=Unknown host as policy_distribution_point
=INPUT=
network:n1 = { ip6 = ::a01:100/120; }
router:r = {
 managed;
 model = ASA;
 policy_distribution_point = host:h1;
 interface:n1 = { ip6 = ::a01:101; hardware = n1; }
}
=WARNING=
Warning: Ignoring undefined host:h1 in 'policy_distribution_point' of router:r
=END=

############################################################
